import { MarketingLayout, ContentBreadcrumb } from "@/components/marketing";
import { SEOHead, SchemaMarkup, createFAQSchema } from "@/components/seo";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { TemplateDownloadGate } from "@/components/marketing/TemplateDownloadGate";
import { Link } from "react-router-dom";
import { 
  FileText, 
  Shield, 
  CheckCircle2, 
  Lock,
  ArrowRight,
  Sparkles,
  FileCheck,
  Scale,
  Building2,
  Users,
  BarChart3,
  Eye
} from "lucide-react";

const sampleReports = [
  {
    id: "classification-memo",
    title: "Classification Memo",
    description: "A complete AI system classification document showing the AI definition test, prohibited practices screening, high-risk assessment, and transparency obligations check.",
    pages: "4 pages",
    format: "PDF",
    icon: Scale,
    preview: [
      "AI System Definition Test Results",
      "Prohibited Practices Screening (Article 5)",
      "High-Risk Candidate Assessment (Annex III)",
      "Transparency Obligations (Article 50)",
      "Classification Rationale & Confidence Level",
    ],
    useCase: "Share with leadership, legal team, or auditors to demonstrate AI Act classification methodology",
    fileName: "sample-classification-memo.pdf",
    badge: "Most Popular",
    badgeVariant: "default" as const,
  },
  {
    id: "fria-report",
    title: "FRIA Report",
    description: "A Fundamental Rights Impact Assessment report compliant with Article 27, including risk identification, mitigation measures, and oversight documentation.",
    pages: "8 pages",
    format: "PDF",
    icon: Shield,
    preview: [
      "Process & Purpose Description",
      "Affected Groups Analysis",
      "Fundamental Rights Risk Matrix",
      "Human Oversight Measures",
      "Mitigation & Governance Plan",
      "Complaint Mechanism Documentation",
    ],
    useCase: "Required for high-risk AI systems deployed by public bodies or affecting fundamental rights",
    fileName: "sample-fria-report.pdf",
    badge: "Article 27",
    badgeVariant: "secondary" as const,
  },
  {
    id: "evidence-pack",
    title: "Evidence Pack (ZIP)",
    description: "A complete audit-ready evidence bundle containing all compliance documentation, organized into regulatory-aligned folder structure.",
    pages: "15+ documents",
    format: "ZIP Bundle",
    icon: FileCheck,
    preview: [
      "00_Executive/ — Summary & Table of Contents",
      "01_Inventory/ — System Record & Metadata",
      "02_Classification/ — Memos & Screening Results",
      "03_Transparency_Article50/ — Disclosure Evidence",
      "04_HighRisk_Deployer_Article26/ — Obligations Checklist",
      "05_Evidence/ — All Supporting Documentation",
      "Evidence_Index.csv — Complete Audit Trail",
    ],
    useCase: "Send to customers during procurement, share with auditors, or submit to regulators",
    fileName: "sample-evidence-pack.zip",
    badge: "Audit-Ready",
    badgeVariant: "outline" as const,
  },
];

const trustIndicators = [
  { icon: Building2, label: "Used by 500+ companies" },
  { icon: Users, label: "Trusted by compliance teams" },
  { icon: CheckCircle2, label: "Procurement-approved format" },
  { icon: BarChart3, label: "Saves 40+ hours per system" },
];

const faqItems = [
  {
    question: "Are these real compliance documents?",
    answer: "Yes. These are actual exports generated by Klarvo for sample AI systems. They follow the exact format used by our customers for audits, procurement, and regulatory submissions."
  },
  {
    question: "Can I use these templates for my own AI systems?",
    answer: "The samples show our output format, but each AI system requires its own assessment. Sign up for a free trial to run the classification wizard on your systems and generate customized documentation."
  },
  {
    question: "What makes these audit-ready?",
    answer: "Our exports include version tracking, reviewer sign-offs, evidence indexing, and a regulatory-aligned folder structure. They're designed to meet the documentation requirements of Article 26 (deployer obligations) and Article 27 (FRIA) of the EU AI Act."
  }
];

export default function Samples() {
  const faqSchema = createFAQSchema({ questions: faqItems });

  return (
    <MarketingLayout>
      <SEOHead
        title="Sample EU AI Act Compliance Reports | Klarvo"
        description="Download sample Classification Memos, FRIA Reports, and Evidence Packs. See exactly what audit-ready EU AI Act compliance documentation looks like."
        keywords={["EU AI Act sample reports", "classification memo example", "FRIA template", "evidence pack sample", "AI compliance documentation"]}
        canonical="/samples"
      />
      <SchemaMarkup schema={faqSchema} />

      <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
        {/* Hero Section */}
        <section className="py-16 md:py-24">
          <div className="container max-w-6xl mx-auto px-4">
            <ContentBreadcrumb 
              currentHref="/samples" 
              customTrail={[
                { name: "Home", href: "/" },
                { name: "Resources", href: "/resources" },
                { name: "Sample Reports", href: "/samples" }
              ]}
            />
            
            <div className="text-center max-w-3xl mx-auto mt-8">
              <Badge variant="outline" className="mb-4 gap-1.5">
                <Eye className="h-3.5 w-3.5" />
                See Before You Build
              </Badge>
              
              <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">
                Sample Compliance Reports
              </h1>
              
              <p className="text-xl text-muted-foreground mb-8 leading-relaxed">
                See exactly what audit-ready EU AI Act documentation looks like. 
                Download real examples of Classification Memos, FRIA Reports, and 
                complete Evidence Packs.
              </p>

              {/* Trust indicators */}
              <div className="flex flex-wrap justify-center gap-6 text-sm text-muted-foreground">
                {trustIndicators.map((indicator) => (
                  <div key={indicator.label} className="flex items-center gap-2">
                    <indicator.icon className="h-4 w-4 text-primary" />
                    <span>{indicator.label}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Sample Reports Grid */}
        <section className="pb-16 md:pb-24">
          <div className="container max-w-6xl mx-auto px-4">
            <div className="space-y-8">
              {sampleReports.map((report) => (
                <Card 
                  key={report.id} 
                  className="overflow-hidden border-2 hover:border-primary/20 transition-colors"
                >
                  <CardContent className="p-0">
                    <div className="grid md:grid-cols-5 gap-0">
                      {/* Preview Section - Left */}
                      <div className="md:col-span-2 bg-muted/30 p-6 md:p-8 border-b md:border-b-0 md:border-r">
                        <div className="flex items-start gap-4 mb-6">
                          <div className="p-3 rounded-xl bg-primary/10">
                            <report.icon className="h-6 w-6 text-primary" />
                          </div>
                          <div>
                            <div className="flex items-center gap-2 mb-1">
                              <h2 className="text-xl font-semibold">{report.title}</h2>
                              <Badge variant={report.badgeVariant} className="text-xs">
                                {report.badge}
                              </Badge>
                            </div>
                            <p className="text-sm text-muted-foreground">
                              {report.pages} • {report.format}
                            </p>
                          </div>
                        </div>

                        {/* Document Preview Mock */}
                        <div className="bg-background rounded-lg border shadow-sm p-4 space-y-2">
                          <div className="flex items-center gap-2 pb-2 border-b mb-3">
                            <FileText className="h-4 w-4 text-muted-foreground" />
                            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                              Contents Preview
                            </span>
                          </div>
                          {report.preview.map((item, index) => (
                            <div 
                              key={index}
                              className="flex items-start gap-2 text-sm"
                            >
                              <CheckCircle2 className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                              <span className="text-muted-foreground">{item}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Details Section - Right */}
                      <div className="md:col-span-3 p-6 md:p-8 flex flex-col justify-between">
                        <div>
                          <p className="text-muted-foreground mb-6 leading-relaxed">
                            {report.description}
                          </p>

                          <div className="bg-muted/30 rounded-lg p-4 mb-6">
                            <h3 className="text-sm font-medium mb-2 flex items-center gap-2">
                              <Sparkles className="h-4 w-4 text-primary" />
                              When to use this
                            </h3>
                            <p className="text-sm text-muted-foreground">
                              {report.useCase}
                            </p>
                          </div>
                        </div>

                        <div className="flex flex-col sm:flex-row gap-3">
                          <TemplateDownloadGate
                            templateName={report.title}
                            templateSlug={report.id}
                            fileName={report.fileName}
                            buttonText={`Download ${report.format}`}
                            buttonSize="lg"
                            className="flex-1"
                          />
                          <Button 
                            variant="outline" 
                            size="lg"
                            asChild
                            className="gap-2"
                          >
                            <Link to="/auth/signup">
                              <Lock className="h-4 w-4" />
                              Create Your Own
                            </Link>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 md:py-24 bg-primary/5 border-t">
          <div className="container max-w-4xl mx-auto px-4 text-center">
            <h2 className="text-3xl font-bold mb-4">
              Ready to generate your own compliance packs?
            </h2>
            <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
              Get your AI systems classified and documented in hours, not weeks. 
              Export audit-ready evidence packs with one click.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" className="btn-premium gap-2" asChild>
                <Link to="/auth/signup">
                  Start Free Trial
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/features">
                  See All Features
                </Link>
              </Button>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="py-16 border-t">
          <div className="container max-w-3xl mx-auto px-4">
            <h2 className="text-2xl font-bold mb-8 text-center">
              Frequently Asked Questions
            </h2>
            <div className="space-y-6">
              {faqItems.map((faq, index) => (
                <div key={index} className="bg-card rounded-lg border p-6">
                  <h3 className="font-semibold mb-2">{faq.question}</h3>
                  <p className="text-muted-foreground">{faq.answer}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>
    </MarketingLayout>
  );
}
