import { Link } from "react-router-dom";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { CTASection, TemplateDownloadGate } from "@/components/marketing";
import { SEOHead, SchemaMarkup, createHowToSchema, createFAQSchema, createBreadcrumbSchema } from "@/components/seo";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  CheckCircle,
  ArrowRight,
  AlertTriangle,
  FileText,
  Users,
  Eye,
  Database,
  Bell
} from "lucide-react";

const checklistItems = [
  {
    icon: FileText,
    title: "Use According to Instructions",
    description: "Ensure the AI system is used according to the provider's instructions for use.",
    evidence: "Instructions document, internal SOP"
  },
  {
    icon: Users,
    title: "Assign Competent Human Oversight",
    description: "Assign oversight to persons with necessary competence, training, and authority.",
    evidence: "Oversight role assignment, training records"
  },
  {
    icon: Database,
    title: "Manage Input Data Quality",
    description: "Ensure input data is relevant and representative (if under your control).",
    evidence: "Data quality checks, sampling notes"
  },
  {
    icon: Eye,
    title: "Monitor Operation",
    description: "Monitor the AI system's operation per the provider's instructions.",
    evidence: "Monitoring plan, periodic reports"
  },
  {
    icon: AlertTriangle,
    title: "Risk Escalation & Suspension",
    description: "Inform provider and suspend use if you suspect risk to health, safety, or fundamental rights.",
    evidence: "Escalation SOP, incident playbook"
  },
  {
    icon: Bell,
    title: "Serious Incident Reporting",
    description: "Report serious incidents to provider and relevant authorities.",
    evidence: "Incident record template, notification records"
  },
  {
    icon: Database,
    title: "Keep Logs (≥6 months)",
    description: "Keep automatically generated logs under your control for at least 6 months.",
    evidence: "Retention policy, system config"
  },
  {
    icon: Users,
    title: "Workplace Notification",
    description: "If used in workplace, inform workers/representatives before deployment.",
    evidence: "Worker notice, communication records"
  },
];

const faqQuestions = [
  {
    question: "What is Article 26 of the EU AI Act?",
    answer: "Article 26 sets out obligations for deployers (users) of high-risk AI systems. It covers requirements for human oversight, data management, monitoring, incident reporting, and transparency."
  },
  {
    question: "Who is a 'deployer' under the EU AI Act?",
    answer: "A deployer is any natural or legal person using an AI system under their authority, except where the AI system is used in the course of a personal non-professional activity."
  },
  {
    question: "How long must I keep AI system logs?",
    answer: "Deployers must keep logs automatically generated by high-risk AI systems under their control for at least 6 months, unless otherwise provided by applicable law."
  },
  {
    question: "When do I need to notify workers?",
    answer: "If you're using a high-risk AI system in a workplace context, you must inform workers and their representatives before putting the system into use."
  }
];

const howToSteps = [
  { name: "Identify high-risk systems", text: "Determine which of your AI systems are classified as high-risk under Annex III or as safety components." },
  { name: "Review provider instructions", text: "Obtain and review the instructions for use from your AI system provider." },
  { name: "Assign oversight", text: "Designate competent persons with authority to oversee and intervene in the AI system's operation." },
  { name: "Set up monitoring", text: "Establish monitoring processes aligned with provider instructions and your context of use." },
  { name: "Prepare incident procedures", text: "Create escalation and incident reporting procedures before deployment." },
  { name: "Notify stakeholders", text: "If applicable, inform workers and representatives before putting the system into use." },
];

export default function Article26Checklist() {
  const howToSchema = createHowToSchema({
    name: "How to Comply with Article 26 Deployer Obligations",
    description: "Step-by-step guide to meeting EU AI Act Article 26 requirements for high-risk AI system deployers.",
    steps: howToSteps,
    totalTime: "PT1H"
  });

  const faqSchema = createFAQSchema({ questions: faqQuestions });

  const breadcrumbSchema = createBreadcrumbSchema({
    items: [
      { name: "Home", url: "https://klarvo.io" },
      { name: "Templates", url: "https://klarvo.io/templates" },
      { name: "Article 26 Checklist", url: "https://klarvo.io/templates/article-26-checklist" }
    ]
  });

  return (
    <MarketingLayout>
      <SEOHead
        title="Article 26 Deployer Checklist - EU AI Act"
        description="Free Article 26 deployer obligations checklist for high-risk AI systems. Covers oversight, monitoring, logs, incidents, and worker notification requirements."
        keywords={["Article 26 checklist", "deployer obligations EU AI Act", "high-risk AI checklist", "AI deployer requirements", "Article 26 compliance"]}
        canonical="https://klarvo.io/templates/article-26-checklist"
      />
      <SchemaMarkup schema={[howToSchema, faqSchema, breadcrumbSchema]} />

      {/* Hero */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-2 mb-4">
              <Badge>Free Template</Badge>
              <Badge variant="destructive">High-Risk Required</Badge>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-6">
              Article 26 Deployer Checklist
            </h1>
            <p className="text-xl text-muted-foreground mb-8">
              Complete checklist for high-risk AI deployer obligations under Article 26 of the EU AI Act. 
              Covers oversight, monitoring, logs, incidents, and workplace notification.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <TemplateDownloadGate
                templateName="Article 26 Checklist"
                templateSlug="article-26-checklist"
                fileName="article-26-checklist.pdf"
                buttonText="Download Checklist"
                buttonSize="lg"
              />
              <Button size="lg" variant="outline" asChild>
                <a href="https://app.klarvo.io/auth/signup">
                  Import to Klarvo
                  <ArrowRight className="ml-2 h-5 w-5" />
                </a>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Checklist Items */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Deployer Obligations Checklist</h2>
            <div className="space-y-4">
              {checklistItems.map((item, index) => (
                <Card key={index}>
                  <CardContent className="p-6">
                    <div className="flex gap-4">
                      <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                        <item.icon className="h-6 w-6 text-primary" />
                      </div>
                      <div className="flex-1">
                        <h3 className="font-semibold mb-1">{item.title}</h3>
                        <p className="text-sm text-muted-foreground mb-2">{item.description}</p>
                        <div className="flex items-center gap-2 text-xs">
                          <Badge variant="outline">Evidence needed:</Badge>
                          <span className="text-muted-foreground">{item.evidence}</span>
                        </div>
                      </div>
                      <CheckCircle className="h-5 w-5 text-muted-foreground/30" />
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Related Resources */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Related Resources</h2>
            <div className="grid gap-6 md:grid-cols-2">
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Article 26 Guide</CardTitle>
                  <CardDescription>Detailed explanation of deployer obligations with examples.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Button asChild variant="link" className="p-0">
                    <Link to="/guides/article-26-deployer-obligations">Read Guide <ArrowRight className="ml-1 h-4 w-4" /></Link>
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">High-Risk Checker</CardTitle>
                  <CardDescription>Check if your AI system is high-risk under Annex III.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Button asChild variant="link" className="p-0">
                    <Link to="/tools/high-risk-checker-annex-iii">Run Checker <ArrowRight className="ml-1 h-4 w-4" /></Link>
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4 max-w-3xl">
          <h2 className="text-3xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqQuestions.map((faq, index) => (
              <div key={index} className="bg-background rounded-lg p-6 shadow-sm">
                <h3 className="font-semibold text-lg mb-2">{faq.question}</h3>
                <p className="text-muted-foreground">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <CTASection
        title="Automate Your Article 26 Compliance"
        subtitle="Klarvo auto-generates deployer checklists based on your AI system classification."
        primaryCta={{ label: "Start Free", href: "https://app.klarvo.io/auth/signup" }}
        secondaryCta={{ label: "See All Templates", href: "/templates" }}
      />
    </MarketingLayout>
  );
}
