import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors } from "@/lib/pdfStyles";
import { KLARVO_LOGO_URL } from "@/lib/pdfAssets";

const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  checklistTable: {
    marginTop: 10,
  },
  checklistHeader: {
    flexDirection: "row",
    backgroundColor: colors.emerald,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  checklistHeaderText: {
    fontSize: 9,
    fontWeight: 700,
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  checklistRow: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
    backgroundColor: "#fff",
  },
  checklistRowAlt: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
    backgroundColor: colors.gray[50],
  },
  checklistItem: {
    width: "70%",
    fontSize: 9,
    color: colors.gray[800],
  },
  checklistStatus: {
    width: "30%",
    fontSize: 9,
    textAlign: "center",
    fontWeight: 600,
  },
  statusCompliant: {
    color: colors.success,
  },
  statusNonCompliant: {
    color: colors.danger,
  },
  statusPending: {
    color: colors.warning,
  },
  providerCard: {
    backgroundColor: colors.gray[50],
    borderWidth: 1,
    borderColor: colors.gray[200],
    borderRadius: 6,
    padding: 16,
    marginTop: 10,
  },
  providerCardTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.gray[800],
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
});

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>Importer Verification — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer
function RunningFooter() {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export interface ImporterVerificationData {
  id: string;
  ai_system_id: string;
  verification_data: Record<string, boolean | null>;
  provider_name: string | null;
  provider_address: string | null;
  provider_contact: string | null;
  authorised_rep_name: string | null;
  authorised_rep_address: string | null;
  status: string;
  non_compliance_details: string | null;
  corrective_actions_taken: string | null;
  verified_by: string | null;
  verified_at: string | null;
  notes: string | null;
  created_at: string;
}

interface ImporterVerificationPDFProps {
  verification: ImporterVerificationData;
  systemName: string;
  organizationName: string;
  verifierName?: string;
  generatedBy: string;
}

const CHECKLIST_LABELS: Record<string, string> = {
  conformity_assessment_carried_out: "Conformity assessment has been carried out by provider",
  technical_documentation_available: "Technical documentation is available upon request",
  instructions_for_use_available: "Instructions for use accompany the AI system",
  ce_marking_affixed: "CE marking is correctly affixed",
  doc_accompanies_system: "EU declaration of conformity accompanies the system",
  provider_identified: "Provider is identified on the system or packaging",
  authorised_rep_appointed: "Authorised representative is appointed (if provider outside EU)",
  contact_point_established: "Contact point for national authorities is established",
  storage_transport_compliant: "Storage and transport conditions are compliant",
  corrective_actions_cooperated: "Cooperation with corrective actions is confirmed",
};

function getStatusText(value: boolean | null): string {
  if (value === true) return "✓ Verified";
  if (value === false) return "✗ Not Verified";
  return "○ Pending";
}

function getStatusStyle(value: boolean | null) {
  if (value === true) return styles.statusCompliant;
  if (value === false) return styles.statusNonCompliant;
  return styles.statusPending;
}

export function ImporterVerificationPDF({
  verification,
  systemName,
  organizationName,
  verifierName,
  generatedBy,
}: ImporterVerificationPDFProps) {
  const generatedDate = format(new Date(), "PPP");
  const checklistItems = Object.entries(verification.verification_data || {});
  const completedCount = checklistItems.filter(([_, v]) => v === true).length;
  const totalCount = checklistItems.length || Object.keys(CHECKLIST_LABELS).length;
  const completionPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  const statusDisplay = verification.status?.replace(/_/g, " ").toUpperCase() || "PENDING";

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={baseStyles.coverPage}>
        <View>
          <Image src={KLARVO_LOGO_URL} style={{ width: 80, marginBottom: 25 }} />
          <Text style={baseStyles.coverBadge}>EU AI ACT — ARTICLE 23</Text>
          <Text style={baseStyles.coverTitle}>Importer Verification</Text>
          <Text style={baseStyles.coverSubtitle}>Market Access Compliance Record</Text>
          <Text style={baseStyles.coverSystemName}>{systemName}</Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Organization: </Text>{organizationName}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Provider: </Text>{verification.provider_name || "Not specified"}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Status: </Text>{statusDisplay}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Completion: </Text>{completionPercent}% ({completedCount} of {totalCount} verified)
          </Text>
        </View>

        <View style={baseStyles.coverFooter}>
          <Text style={{ fontSize: 10, color: colors.gray[500], marginBottom: 4 }}>
            Generated: {generatedDate}{generatedBy ? ` by ${generatedBy}` : ""}
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[400] }}>
            Importers must verify provider compliance before placing AI systems on the EU market.
          </Text>
        </View>
      </Page>

      {/* Verification Record */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter />

        {/* Overview Section */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>1. Verification Overview</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>AI System:</Text>
            <Text style={baseStyles.rowValue}>{systemName}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Importer Organization:</Text>
            <Text style={baseStyles.rowValue}>{organizationName}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verification Status:</Text>
            <Text style={baseStyles.rowValue}>{statusDisplay}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verified By:</Text>
            <Text style={baseStyles.rowValue}>{verifierName || "Pending verification"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verified Date:</Text>
            <Text style={baseStyles.rowValue}>
              {verification.verified_at ? format(new Date(verification.verified_at), "PPP") : "Not yet verified"}
            </Text>
          </View>
        </View>

        {/* Provider Information */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>2. Provider Information</Text>
          <View style={styles.providerCard}>
            <Text style={styles.providerCardTitle}>Provider Details</Text>
            <View style={baseStyles.row}>
              <Text style={baseStyles.rowLabel}>Provider Name:</Text>
              <Text style={baseStyles.rowValue}>{verification.provider_name || "Not specified"}</Text>
            </View>
            <View style={baseStyles.row}>
              <Text style={baseStyles.rowLabel}>Address:</Text>
              <Text style={baseStyles.rowValue}>{verification.provider_address || "Not specified"}</Text>
            </View>
            <View style={baseStyles.row}>
              <Text style={baseStyles.rowLabel}>Contact:</Text>
              <Text style={baseStyles.rowValue}>{verification.provider_contact || "Not specified"}</Text>
            </View>
          </View>

          {(verification.authorised_rep_name || verification.authorised_rep_address) && (
            <View style={[styles.providerCard, { marginTop: 12 }]}>
              <Text style={styles.providerCardTitle}>Authorised Representative (Non-EU Provider)</Text>
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>Representative Name:</Text>
                <Text style={baseStyles.rowValue}>{verification.authorised_rep_name || "Not applicable"}</Text>
              </View>
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>Address:</Text>
                <Text style={baseStyles.rowValue}>{verification.authorised_rep_address || "Not applicable"}</Text>
              </View>
            </View>
          )}
        </View>

        {/* Article 23 Checklist */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>3. Article 23 Verification Checklist</Text>
          <Text style={baseStyles.paragraph}>
            Before placing a high-risk AI system on the market, importers must verify the following 
            obligations have been met by the provider in accordance with Article 23 of the EU AI Act.
          </Text>

          <View style={styles.checklistTable}>
            <View style={styles.checklistHeader}>
              <Text style={[styles.checklistHeaderText, { width: "70%" }]}>Requirement</Text>
              <Text style={[styles.checklistHeaderText, { width: "30%", textAlign: "center" }]}>Status</Text>
            </View>
            {(checklistItems.length > 0 ? checklistItems : Object.entries(CHECKLIST_LABELS).map(([k]) => [k, null] as [string, boolean | null])).map(([key, value], idx) => (
              <View key={key} style={idx % 2 === 0 ? styles.checklistRow : styles.checklistRowAlt} wrap={false}>
                <Text style={styles.checklistItem}>
                  {CHECKLIST_LABELS[key] || key.replace(/_/g, " ")}
                </Text>
                <Text style={[styles.checklistStatus, getStatusStyle(value)]}>
                  {getStatusText(value)}
                </Text>
              </View>
            ))}
          </View>
        </View>
      </Page>

      {/* Page 2: Non-compliance, Notes, Signature */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter />

        {/* Non-compliance & Corrective Actions */}
        {(verification.non_compliance_details || verification.corrective_actions_taken) && (
          <View style={baseStyles.sectionKeepTogether}>
            <Text style={baseStyles.sectionTitle}>4. Non-Compliance & Corrective Actions</Text>
            {verification.non_compliance_details && (
              <View style={baseStyles.dangerBox} wrap={false}>
                <Text style={{ fontSize: 10, fontWeight: 700, color: colors.danger, marginBottom: 6 }}>
                  Non-Compliance Identified
                </Text>
                <Text style={baseStyles.dangerBoxText}>{verification.non_compliance_details}</Text>
              </View>
            )}
            {verification.corrective_actions_taken && (
              <View style={baseStyles.infoBox} wrap={false}>
                <Text style={{ fontSize: 10, fontWeight: 700, color: colors.emerald, marginBottom: 6 }}>
                  Corrective Actions Taken
                </Text>
                <Text style={baseStyles.infoBoxText}>{verification.corrective_actions_taken}</Text>
              </View>
            )}
          </View>
        )}

        {/* Notes */}
        {verification.notes && (
          <View style={baseStyles.sectionKeepTogether}>
            <Text style={baseStyles.sectionTitle}>5. Additional Notes</Text>
            <View style={baseStyles.infoBox}>
              <Text style={baseStyles.infoBoxText}>{verification.notes}</Text>
            </View>
          </View>
        )}

        {/* Signature Section */}
        <View style={baseStyles.signatureSection} wrap={false}>
          <Text style={[baseStyles.h2, { marginTop: 0, marginBottom: 15 }]}>Verification Sign-off</Text>
          <Text style={baseStyles.paragraph}>
            This verification record confirms that the importer has performed due diligence checks
            on the provider's compliance with EU AI Act requirements before placing the AI system on the market.
          </Text>
          <View style={baseStyles.signatureRow}>
            <View style={baseStyles.signatureBlock}>
              <View style={baseStyles.signatureLine} />
              <Text style={baseStyles.signatureLabel}>Verified By</Text>
              {verifierName && (
                <Text style={{ fontSize: 9, color: colors.gray[800], marginTop: 2 }}>{verifierName}</Text>
              )}
              <Text style={{ fontSize: 8, color: colors.gray[500], marginTop: 2 }}>
                {verification.verified_at ? format(new Date(verification.verified_at), "PPP") : "Date: _______________"}
              </Text>
            </View>
            <View style={baseStyles.signatureBlock}>
              <View style={baseStyles.signatureLine} />
              <Text style={baseStyles.signatureLabel}>Compliance Officer Approval</Text>
              <Text style={{ fontSize: 8, color: colors.gray[500], marginTop: 2 }}>Date: _______________</Text>
            </View>
          </View>
        </View>

        {/* Legal Notice */}
        <View style={[baseStyles.warningBox, { marginTop: 20 }]} wrap={false}>
          <Text style={baseStyles.warningBoxText}>
            Article 23 Obligations: Importers must ensure the provider has carried out a conformity assessment,
            technical documentation is available, the AI system bears CE marking and is accompanied by an EU 
            declaration of conformity and instructions for use. Non-compliant systems must not be placed on the market.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
