import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors, formatValue } from "@/lib/pdfStyles";
import { KLARVO_LOGO_URL } from "@/lib/pdfAssets";

// Extended styles for AI System Evidence Pack
const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  coverPage: {
    padding: 60,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 16,
    color: colors.gray[900],
    textAlign: "center",
  },
  coverSubtitle: {
    fontSize: 16,
    color: colors.gray[500],
    textAlign: "center",
    marginBottom: 40,
  },
  coverMeta: {
    marginTop: 60,
    padding: 20,
    backgroundColor: colors.gray[50],
    borderRadius: 8,
    width: "80%",
  },
  coverMetaRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  coverMetaLabel: {
    width: "40%",
    fontWeight: 600,
    color: colors.gray[700],
    fontSize: 10,
  },
  coverMetaValue: {
    width: "60%",
    color: colors.gray[800],
    fontSize: 10,
  },
  watermark: {
    position: "absolute",
    top: "45%",
    left: "25%",
    fontSize: 60,
    color: colors.gray[200],
    transform: "rotate(-45deg)",
    opacity: 0.3,
  },
  badgeHighRisk: {
    backgroundColor: colors.dangerLight,
    color: colors.danger,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: 600,
  },
  badgeLimitedRisk: {
    backgroundColor: colors.warningLight,
    color: colors.warning,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: 600,
  },
  badgeMinimalRisk: {
    backgroundColor: colors.successLight,
    color: colors.success,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: 600,
  },
  badgeNotClassified: {
    backgroundColor: colors.gray[100],
    color: colors.gray[600],
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    fontSize: 9,
    fontWeight: 600,
  },
});

interface AISystemData {
  id: string;
  name: string;
  description?: string | null;
  department?: string | null;
  lifecycle_status: string;
  vendor?: { name: string } | null;
  primary_owner?: { full_name: string | null } | null;
  oversight_model?: string | null;
  human_involvement?: string | null;
  oversight_sop_status?: string | null;
  operators_trained?: string | null;
  has_automatic_logs?: string | null;
  log_storage_location?: string | null;
  log_retention_period?: string | null;
  can_export_logs?: string | null;
  processes_personal_data?: string | null;
  special_category_data?: string | null;
  dpia_status?: string | null;
  training_exists?: string | null;
  training_completion_status?: string | null;
  classification?: {
    risk_level: string;
    is_ai_system?: boolean | null;
    has_prohibited_indicators?: boolean | null;
    is_high_risk_candidate?: boolean | null;
    has_transparency_obligations?: boolean | null;
    high_risk_categories?: string[] | null;
    transparency_categories?: string[] | null;
    classification_rationale?: string | null;
    classified_at?: string | null;
  } | null;
  created_at: string;
}

interface Props {
  system: AISystemData;
  organization: { name: string };
  generatedBy: string;
  showWatermark?: boolean;
}

const getRiskBadgeStyle = (riskLevel: string) => {
  switch (riskLevel) {
    case "high_risk":
      return styles.badgeHighRisk;
    case "limited_risk":
      return styles.badgeLimitedRisk;
    case "minimal_risk":
      return styles.badgeMinimalRisk;
    default:
      return styles.badgeNotClassified;
  }
};

const formatRiskLevel = (level: string) => {
  switch (level) {
    case "high_risk":
      return "High Risk";
    case "limited_risk":
      return "Limited Risk (Transparency)";
    case "minimal_risk":
      return "Minimal Risk";
    case "prohibited":
      return "Prohibited";
    default:
      return "Not Classified";
  }
};

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>{systemName} - Evidence Pack</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer with dynamic page numbers
function RunningFooter() {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export function AISystemPDF({ system, organization, generatedBy, showWatermark = false }: Props) {
  const classification = system.classification;
  const generatedDate = format(new Date(), "PPP");
  const documentVersion = "1.0";

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={{ padding: 40, fontFamily: "Helvetica", fontSize: 10 }}>
        {showWatermark && <Text style={styles.watermark}>SAMPLE REPORT</Text>}
        <View style={styles.coverPage}>
          <Image src={KLARVO_LOGO_URL} style={{ width: 80, marginBottom: 20 }} />
          <Text style={styles.coverTitle}>AI System Evidence Pack</Text>
          <Text style={styles.coverSubtitle}>{system.name}</Text>
          <Text style={{ fontSize: 12, color: colors.gray[500], marginBottom: 20 }}>
            EU AI Act Compliance Documentation
          </Text>
          
          <View style={styles.coverMeta}>
            <View style={styles.coverMetaRow}>
              <Text style={styles.coverMetaLabel}>Organization:</Text>
              <Text style={styles.coverMetaValue}>{organization.name}</Text>
            </View>
            <View style={styles.coverMetaRow}>
              <Text style={styles.coverMetaLabel}>Document Version:</Text>
              <Text style={styles.coverMetaValue}>{documentVersion}</Text>
            </View>
            <View style={styles.coverMetaRow}>
              <Text style={styles.coverMetaLabel}>Generated Date:</Text>
              <Text style={styles.coverMetaValue}>{generatedDate}</Text>
            </View>
            <View style={styles.coverMetaRow}>
              <Text style={styles.coverMetaLabel}>Generated By:</Text>
              <Text style={styles.coverMetaValue}>{generatedBy}</Text>
            </View>
            <View style={styles.coverMetaRow}>
              <Text style={styles.coverMetaLabel}>Classification:</Text>
              <Text style={styles.coverMetaValue}>Internal / Shareable with Auditors</Text>
            </View>
          </View>
        </View>
        <View style={baseStyles.runningFooter}>
          <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
          <Text style={baseStyles.footerPage}>Cover Page</Text>
        </View>
      </Page>

      {/* Table of Contents */}
      <Page size="A4" style={styles.page}>
        {showWatermark && <Text style={styles.watermark}>FREE TIER</Text>}
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter />
        
        <View style={baseStyles.section}>
          <Text style={baseStyles.sectionTitle}>Table of Contents</Text>
          
          {[
            ["1. Executive Summary", "3"],
            ["2. System Overview", "3"],
            ["3. EU AI Act Classification", "3"],
            ["4. Applicable Obligations", "4"],
            ["5. Human Oversight", "4"],
            ["6. Logging & Record-keeping", "5"],
            ["7. Data & Privacy", "5"],
            ["8. Training & AI Literacy", "5"],
            ["9. Vendor Information", "6"],
          ].map(([section, page], i) => (
            <View key={i} style={baseStyles.tocItem}>
              <Text style={baseStyles.tocSection}>{section}</Text>
              <Text style={baseStyles.tocPage}>{page}</Text>
            </View>
          ))}
        </View>
      </Page>

      {/* Page 3: Executive Summary & System Overview */}
      <Page size="A4" style={styles.page}>
        {showWatermark && <Text style={styles.watermark}>FREE TIER</Text>}
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter />

        {/* Executive Summary */}
        <View style={baseStyles.sectionKeepTogether} wrap={false}>
          <Text style={baseStyles.sectionTitle}>1. Executive Summary</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>System Name</Text>
            <Text style={baseStyles.rowValue}>{system.name}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Risk Level</Text>
            <View style={getRiskBadgeStyle(classification?.risk_level || "not_classified")}>
              <Text>{formatRiskLevel(classification?.risk_level || "not_classified")}</Text>
            </View>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Status</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.lifecycle_status)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Owner</Text>
            <Text style={baseStyles.rowValue}>{system.primary_owner?.full_name || "Unassigned"}</Text>
          </View>
        </View>

        {/* System Overview */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>2. System Overview</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Description</Text>
            <Text style={baseStyles.rowValue}>{system.description || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Department</Text>
            <Text style={baseStyles.rowValue}>{system.department || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Vendor</Text>
            <Text style={baseStyles.rowValue}>{system.vendor?.name || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Created</Text>
            <Text style={baseStyles.rowValue}>{format(new Date(system.created_at), "PPP")}</Text>
          </View>
        </View>

        {/* Classification */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>3. EU AI Act Classification</Text>
          {classification ? (
            <>
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>Is AI System</Text>
                <Text style={baseStyles.rowValue}>
                  {classification.is_ai_system === true ? "Yes" : classification.is_ai_system === false ? "No" : "Not assessed"}
                </Text>
              </View>
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>Prohibited Indicators</Text>
                <Text style={baseStyles.rowValue}>
                  {classification.has_prohibited_indicators === true ? "Yes - Review Required" : "None Found"}
                </Text>
              </View>
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>High-Risk Candidate</Text>
                <Text style={baseStyles.rowValue}>
                  {classification.is_high_risk_candidate === true ? "Yes" : "No"}
                </Text>
              </View>
              {classification.high_risk_categories && classification.high_risk_categories.length > 0 && (
                <View style={baseStyles.row}>
                  <Text style={baseStyles.rowLabel}>High-Risk Categories</Text>
                  <Text style={baseStyles.rowValue}>{classification.high_risk_categories.join(", ")}</Text>
                </View>
              )}
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>Transparency Obligations</Text>
                <Text style={baseStyles.rowValue}>
                  {classification.has_transparency_obligations === true ? "Yes" : "No"}
                </Text>
              </View>
              {classification.classification_rationale && (
                <View style={baseStyles.row}>
                  <Text style={baseStyles.rowLabel}>Rationale</Text>
                  <Text style={baseStyles.rowValue}>{classification.classification_rationale}</Text>
                </View>
              )}
              {classification.classified_at && (
                <View style={baseStyles.row}>
                  <Text style={baseStyles.rowLabel}>Classified Date</Text>
                  <Text style={baseStyles.rowValue}>{format(new Date(classification.classified_at), "PPP")}</Text>
                </View>
              )}
            </>
          ) : (
            <Text style={baseStyles.paragraph}>
              This AI system has not been classified yet. Complete the classification wizard to assess risk level.
            </Text>
          )}
        </View>
      </Page>

      {/* Page 4: Applicable Obligations & Human Oversight */}
      <Page size="A4" style={styles.page}>
        {showWatermark && <Text style={styles.watermark}>FREE TIER</Text>}
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter />

        {/* Applicable Obligations */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>4. Applicable Obligations</Text>
          {classification?.risk_level === "high_risk" ? (
            <>
              <View style={baseStyles.warningBox} wrap={false}>
                <Text style={baseStyles.warningBoxText}>
                  As a high-risk AI system, deployer obligations under Article 26 apply. These requirements ensure proper use, oversight, and accountability.
                </Text>
              </View>
              <View style={baseStyles.table}>
                <View style={baseStyles.tableHeader}>
                  <Text style={baseStyles.tableCellWide}>Obligation</Text>
                  <Text style={baseStyles.tableCell}>Reference</Text>
                </View>
                {[
                  ["Use according to provider instructions", "Art. 26(1)"],
                  ["Assign competent human oversight", "Art. 26(2)"],
                  ["Ensure input data relevance & representativeness", "Art. 26(4)"],
                  ["Monitor system operation", "Art. 26(5)"],
                  ["Keep logs for minimum 6 months", "Art. 26(6)"],
                  ["Inform workers (if workplace use)", "Art. 26(7)"],
                ].map(([obligation, ref], idx) => (
                  <View key={idx} style={idx % 2 === 0 ? baseStyles.tableRow : baseStyles.tableRowAlt} wrap={false}>
                    <Text style={baseStyles.tableCellWide}>{obligation}</Text>
                    <Text style={baseStyles.tableCell}>{ref}</Text>
                  </View>
                ))}
              </View>
            </>
          ) : classification?.has_transparency_obligations ? (
            <View style={baseStyles.infoBox} wrap={false}>
              <Text style={baseStyles.infoBoxText}>
                Transparency obligations apply under Article 50. Users must be informed when interacting with AI, and synthetic content must be appropriately marked.
              </Text>
            </View>
          ) : (
            <Text style={baseStyles.paragraph}>
              Based on the current classification, no specific high-risk or transparency obligations apply. Continue to follow AI governance best practices.
            </Text>
          )}
        </View>

        {/* Human Oversight */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>5. Human Oversight</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Oversight Model</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.oversight_model)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Human Involvement</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.human_involvement)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Oversight SOP Status</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.oversight_sop_status)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Operators Trained</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.operators_trained)}</Text>
          </View>
        </View>
      </Page>

      {/* Page 5: Logging, Data & Privacy, Training */}
      <Page size="A4" style={styles.page}>
        {showWatermark && <Text style={styles.watermark}>FREE TIER</Text>}
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter />

        {/* Logging & Record-keeping */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>6. Logging & Record-keeping</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Automatic Logs</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.has_automatic_logs)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Log Storage Location</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.log_storage_location)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Retention Period</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.log_retention_period)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Can Export Logs</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.can_export_logs)}</Text>
          </View>
          {classification?.risk_level === "high_risk" && (
            <View style={baseStyles.infoBox} wrap={false}>
              <Text style={baseStyles.infoBoxText}>
                Article 26(6) requires deployers to keep logs under their control for at least 6 months, unless otherwise specified by law.
              </Text>
            </View>
          )}
        </View>

        {/* Data & Privacy */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>7. Data & Privacy</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Processes Personal Data</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.processes_personal_data)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Special Category Data</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.special_category_data)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>DPIA Status</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.dpia_status)}</Text>
          </View>
        </View>

        {/* Training & AI Literacy */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>8. Training & AI Literacy</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Training Exists</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.training_exists)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Completion Status</Text>
            <Text style={baseStyles.rowValue}>{formatValue(system.training_completion_status)}</Text>
          </View>
          <View style={baseStyles.infoBox} wrap={false}>
            <Text style={baseStyles.infoBoxText}>
              Article 4 requires providers and deployers to take measures to ensure sufficient AI literacy of staff and others operating AI on their behalf.
            </Text>
          </View>
        </View>
      </Page>

      {/* Page 6: Vendor Information */}
      <Page size="A4" style={styles.page}>
        {showWatermark && <Text style={styles.watermark}>FREE TIER</Text>}
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter />

        {/* Vendor Information */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>9. Vendor Information</Text>
          {system.vendor ? (
            <>
              <View style={baseStyles.row}>
                <Text style={baseStyles.rowLabel}>Vendor Name</Text>
                <Text style={baseStyles.rowValue}>{system.vendor.name}</Text>
              </View>
              <Text style={baseStyles.paragraph}>
                For detailed vendor attestations, security documentation, and contract information, refer to the vendor profile in the Klarvo platform.
              </Text>
            </>
          ) : (
            <Text style={baseStyles.paragraph}>
              No vendor associated with this AI system. This may indicate an internally-built system or that vendor information has not been recorded.
            </Text>
          )}
        </View>

        {/* Document Control */}
        <View style={baseStyles.sectionKeepTogether} wrap={false}>
          <Text style={baseStyles.sectionTitle}>Document Control</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Document Version</Text>
            <Text style={baseStyles.rowValue}>{documentVersion}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Generated</Text>
            <Text style={baseStyles.rowValue}>{generatedDate}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Generated By</Text>
            <Text style={baseStyles.rowValue}>{generatedBy}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>System ID</Text>
            <Text style={baseStyles.rowValue}>{system.id}</Text>
          </View>
        </View>

        {/* Disclaimer */}
        <View style={{ marginTop: 40, padding: 15, backgroundColor: colors.gray[50], borderRadius: 4 }} wrap={false}>
          <Text style={{ fontSize: 9, fontWeight: 600, marginBottom: 6, color: colors.gray[700] }}>
            Disclaimer
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[500], lineHeight: 1.4 }}>
            This document is generated based on information entered into the Klarvo platform. It is intended to support EU AI Act compliance efforts but does not constitute legal advice. Organizations should consult qualified legal counsel to ensure full compliance with applicable regulations. The accuracy of this document depends on the completeness and accuracy of the underlying data.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
