import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors, formatYesNoUnsure, formatList, formatRiskLevel, getRiskBadgeStyle } from "@/lib/pdfStyles";

// Extend base styles with memo-specific styles
const styles = StyleSheet.create({
  ...baseStyles,
  page: {
    ...baseStyles.page,
    paddingTop: 60, // Space for running header
  },
  verdictBox: {
    padding: 12,
    marginVertical: 10,
    borderRadius: 4,
    // @ts-ignore - keep together
    minPresenceAhead: 30,
  },
  verdictPass: {
    backgroundColor: colors.successLight,
    borderLeftWidth: 4,
    borderLeftColor: colors.success,
  },
  verdictFail: {
    backgroundColor: colors.dangerLight,
    borderLeftWidth: 4,
    borderLeftColor: colors.danger,
  },
  verdictWarning: {
    backgroundColor: colors.warningLight,
    borderLeftWidth: 4,
    borderLeftColor: colors.warning,
  },
  tableCellSmall: {
    width: 80,
    paddingHorizontal: 4,
    fontSize: 9,
    color: colors.gray[800],
  },
});

// Type definitions
interface AISystemData {
  id: string;
  name: string;
  description?: string | null;
  department?: string | null;
  lifecycle_status: string;
  vendor?: { name: string } | null;
  primary_owner?: { full_name: string | null } | null;
  // Wizard data
  wizard_mode?: string | null;
  summary?: string | null;
  deployment_regions?: string[] | null;
  eu_countries?: string[] | null;
  affected_groups?: string[] | null;
  value_chain_role?: string[] | null;
  // AI Definition
  ai_definition_result?: string | null;
  ai_definition_rationale?: string | null;
  ai_definition_confidence?: string | null;
  infers_outputs?: string | null;
  operates_autonomously?: string | null;
  output_types?: string[] | null;
  technical_approach?: string[] | null;
  // Prohibited Screening
  prohibited_screening_result?: string | null;
  prohibited_screening_notes?: string | null;
  prohibited_manipulation?: string | null;
  prohibited_exploitation?: string | null;
  prohibited_social_scoring?: string | null;
  prohibited_criminal_profiling?: string | null;
  prohibited_facial_scraping?: string | null;
  prohibited_emotion_inference?: string | null;
  prohibited_biometric_categorisation?: string | null;
  prohibited_realtime_biometric?: string | null;
  // High-Risk Screening
  highrisk_screening_result?: string | null;
  highrisk_screening_notes?: string | null;
  highrisk_biometric?: string | null;
  highrisk_critical_infrastructure?: string | null;
  highrisk_education?: string | null;
  highrisk_employment?: string | null;
  highrisk_essential_services?: string | null;
  highrisk_law_enforcement?: string | null;
  highrisk_migration?: string | null;
  highrisk_justice?: string | null;
  highrisk_safety_component?: string | null;
  // Transparency
  transparency_direct_interaction?: string | null;
  transparency_obvious_ai?: string | null;
  transparency_synthetic_content?: string | null;
  transparency_outputs_marked?: string | null;
  transparency_emotion_recognition?: string | null;
  transparency_deepfake?: string | null;
  transparency_public_text?: string | null;
  transparency_status?: string | null;
  // Signoff
  signoff_reviewer_id?: string | null;
  signoff_date?: string | null;
  signoff_notes?: string | null;
  final_classification?: string | null;
  created_at: string;
}

interface ClassificationData {
  risk_level: string;
  is_ai_system?: boolean | null;
  has_prohibited_indicators?: boolean | null;
  is_high_risk_candidate?: boolean | null;
  has_transparency_obligations?: boolean | null;
  high_risk_categories?: string[] | null;
  transparency_categories?: string[] | null;
  classification_rationale?: string | null;
  classified_at?: string | null;
  confidence_level?: string | null;
}

interface Props {
  system: AISystemData;
  classification: ClassificationData | null;
  organization: { name: string };
  generatedBy: string;
  reviewerName?: string;
}

// Running Header Component
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>Classification Memo — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer Component with page numbers
function RunningFooter({ generatedDate }: { generatedDate: string }) {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export function ClassificationMemoPDF({ 
  system, 
  classification, 
  organization, 
  generatedBy,
  reviewerName 
}: Props) {
  const generatedDate = format(new Date(), "PPP");
  
  const prohibitedQuestions = [
    { key: "prohibited_manipulation", label: "Harmful manipulation/deception" },
    { key: "prohibited_exploitation", label: "Exploitation of vulnerabilities" },
    { key: "prohibited_social_scoring", label: "Social scoring" },
    { key: "prohibited_criminal_profiling", label: "Criminal risk profiling" },
    { key: "prohibited_facial_scraping", label: "Untargeted facial scraping" },
    { key: "prohibited_emotion_inference", label: "Workplace/education emotion inference" },
    { key: "prohibited_biometric_categorisation", label: "Sensitive biometric categorisation" },
    { key: "prohibited_realtime_biometric", label: "Real-time remote biometric ID" },
  ];

  const highRiskCategories = [
    { key: "highrisk_biometric", label: "Biometric identification/categorisation" },
    { key: "highrisk_critical_infrastructure", label: "Critical infrastructure" },
    { key: "highrisk_education", label: "Education & vocational training" },
    { key: "highrisk_employment", label: "Employment & worker management" },
    { key: "highrisk_essential_services", label: "Essential services access" },
    { key: "highrisk_law_enforcement", label: "Law enforcement" },
    { key: "highrisk_migration", label: "Migration & border control" },
    { key: "highrisk_justice", label: "Justice & democracy" },
    { key: "highrisk_safety_component", label: "Regulated product safety component" },
  ];

  const hasProhibitedFlags = prohibitedQuestions.some(
    q => system[q.key as keyof AISystemData] === "yes" || system[q.key as keyof AISystemData] === "unsure"
  );

  const hasHighRiskFlags = highRiskCategories.some(
    q => system[q.key as keyof AISystemData] === "yes" || system[q.key as keyof AISystemData] === "unsure"
  );

  return (
    <Document>
      {/* Page 1: Executive Summary & AI Definition Test */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter generatedDate={generatedDate} />
        
        {/* Header */}
        <View style={{ marginBottom: 20, marginTop: 10 }}>
          <Text style={{ fontSize: 22, fontWeight: 700, color: colors.emerald, marginBottom: 4 }}>
            Classification Memo
          </Text>
          <Text style={{ fontSize: 14, color: colors.gray[600], marginBottom: 10 }}>
            {system.name}
          </Text>
          <View style={{ flexDirection: "row", gap: 20 }}>
            <Text style={{ fontSize: 9, color: colors.gray[500] }}>
              Organization: {organization.name}
            </Text>
            <Text style={{ fontSize: 9, color: colors.gray[500] }}>
              Generated: {generatedDate}
            </Text>
            <Text style={{ fontSize: 9, color: colors.gray[500] }}>
              By: {generatedBy}
            </Text>
          </View>
        </View>

        {/* Executive Summary - keep together */}
        <View style={baseStyles.sectionKeepTogether} wrap={false}>
          <Text style={baseStyles.sectionTitle}>1. Executive Summary</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>System Name</Text>
            <Text style={baseStyles.rowValue}>{system.name}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Final Classification</Text>
            <View style={[baseStyles.badge, getRiskBadgeStyle(classification?.risk_level || "not_classified")]}>
              <Text>{formatRiskLevel(classification?.risk_level || "not_classified")}</Text>
            </View>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Confidence Level</Text>
            <Text style={baseStyles.rowValue}>{classification?.confidence_level || system.ai_definition_confidence || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Classification Date</Text>
            <Text style={baseStyles.rowValue}>
              {classification?.classified_at 
                ? format(new Date(classification.classified_at), "PPP") 
                : system.signoff_date 
                  ? format(new Date(system.signoff_date), "PPP")
                  : "—"}
            </Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Reviewer</Text>
            <Text style={baseStyles.rowValue}>{reviewerName || "—"}</Text>
          </View>
          {(classification?.classification_rationale || system.signoff_notes) && (
            <View style={{ marginTop: 8 }}>
              <Text style={baseStyles.h3}>Rationale</Text>
              <Text style={baseStyles.paragraph}>
                {classification?.classification_rationale || system.signoff_notes}
              </Text>
            </View>
          )}
        </View>

        {/* AI System Definition Test */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>2. AI System Definition Test</Text>
          <View style={[
            styles.verdictBox, 
            system.ai_definition_result === "likely_ai" 
              ? styles.verdictPass 
              : system.ai_definition_result === "likely_not"
                ? styles.verdictWarning
                : styles.verdictWarning
          ]} wrap={false}>
            <Text style={{ fontSize: 10, fontWeight: 700 }}>
              Conclusion: {system.ai_definition_result === "likely_ai" 
                ? "Likely an AI System (in scope)" 
                : system.ai_definition_result === "likely_not"
                  ? "Likely NOT an AI System (may be out of scope)"
                  : "Needs Further Review"}
            </Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Infers outputs from inputs</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.infers_outputs)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Operates with autonomy</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.operates_autonomously)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Output types</Text>
            <Text style={baseStyles.rowValue}>{formatList(system.output_types)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Technical approach</Text>
            <Text style={baseStyles.rowValue}>{formatList(system.technical_approach)}</Text>
          </View>
          {system.ai_definition_rationale && (
            <View style={{ marginTop: 8 }}>
              <Text style={baseStyles.h3}>Rationale</Text>
              <Text style={baseStyles.paragraph}>{system.ai_definition_rationale}</Text>
            </View>
          )}
        </View>

        {/* Prohibited Practices Screening */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>3. Prohibited Practices Screening (Article 5)</Text>
          <View style={[
            styles.verdictBox,
            system.prohibited_screening_result === "no_prohibited" 
              ? styles.verdictPass 
              : styles.verdictFail
          ]} wrap={false}>
            <Text style={{ fontSize: 10, fontWeight: 700 }}>
              Result: {system.prohibited_screening_result === "no_prohibited" 
                ? "No prohibited practice indicators found" 
                : system.prohibited_screening_result === "potential_prohibited"
                  ? "POTENTIAL PROHIBITED PRACTICE - Stop & Escalate"
                  : "Needs Legal Review"}
            </Text>
          </View>
          <View style={baseStyles.table}>
            <View style={baseStyles.tableHeader}>
              <Text style={baseStyles.tableCellWide}>Practice</Text>
              <Text style={styles.tableCellSmall}>Answer</Text>
            </View>
            {prohibitedQuestions.map((q, idx) => (
              <View key={q.key} style={idx % 2 === 0 ? baseStyles.tableRow : baseStyles.tableRowAlt} wrap={false}>
                <Text style={baseStyles.tableCellWide}>{q.label}</Text>
                <Text style={styles.tableCellSmall}>
                  {formatYesNoUnsure(system[q.key as keyof AISystemData] as string)}
                </Text>
              </View>
            ))}
          </View>
          {system.prohibited_screening_notes && (
            <View style={{ marginTop: 8 }}>
              <Text style={baseStyles.h3}>Notes</Text>
              <Text style={baseStyles.paragraph}>{system.prohibited_screening_notes}</Text>
            </View>
          )}
        </View>
      </Page>

      {/* Page 2: High-Risk, Transparency, Context */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={system.name} orgName={organization.name} />
        <RunningFooter generatedDate={generatedDate} />

        {/* High-Risk Screening */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>4. High-Risk Screening (Annex III)</Text>
          <View style={[
            styles.verdictBox,
            system.highrisk_screening_result === "not_high_risk"
              ? styles.verdictPass
              : hasHighRiskFlags
                ? styles.verdictFail
                : styles.verdictWarning
          ]} wrap={false}>
            <Text style={{ fontSize: 10, fontWeight: 700 }}>
              Result: {system.highrisk_screening_result === "not_high_risk"
                ? "Not a high-risk candidate"
                : system.highrisk_screening_result === "high_risk_annex_iii"
                  ? "HIGH-RISK CANDIDATE (Annex III)"
                  : system.highrisk_screening_result === "high_risk_product"
                    ? "HIGH-RISK CANDIDATE (Regulated Product)"
                    : "Needs Review"}
            </Text>
          </View>
          <View style={baseStyles.table}>
            <View style={baseStyles.tableHeader}>
              <Text style={baseStyles.tableCellWide}>Category</Text>
              <Text style={styles.tableCellSmall}>Applies?</Text>
            </View>
            {highRiskCategories.map((q, idx) => (
              <View key={q.key} style={idx % 2 === 0 ? baseStyles.tableRow : baseStyles.tableRowAlt} wrap={false}>
                <Text style={baseStyles.tableCellWide}>{q.label}</Text>
                <Text style={styles.tableCellSmall}>
                  {formatYesNoUnsure(system[q.key as keyof AISystemData] as string)}
                </Text>
              </View>
            ))}
          </View>
          {system.highrisk_screening_notes && (
            <View style={{ marginTop: 8 }}>
              <Text style={baseStyles.h3}>Notes</Text>
              <Text style={baseStyles.paragraph}>{system.highrisk_screening_notes}</Text>
            </View>
          )}
        </View>

        {/* Transparency Obligations */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>5. Transparency Obligations (Article 50)</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Direct interaction with persons</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_direct_interaction)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Obviously AI to users</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_obvious_ai)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Generates synthetic content</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_synthetic_content)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Outputs marked as AI-generated</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_outputs_marked)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Emotion recognition/biometric</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_emotion_recognition)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Deepfake generation</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_deepfake)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Public interest text generation</Text>
            <Text style={baseStyles.rowValue}>{formatYesNoUnsure(system.transparency_public_text)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Implementation Status</Text>
            <Text style={baseStyles.rowValue}>{system.transparency_status || "Not assessed"}</Text>
          </View>
        </View>

        {/* Context Information */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>6. System Context</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Description</Text>
            <Text style={baseStyles.rowValue}>{system.description || system.summary || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Department</Text>
            <Text style={baseStyles.rowValue}>{system.department || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Vendor</Text>
            <Text style={baseStyles.rowValue}>{system.vendor?.name || "—"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Primary Owner</Text>
            <Text style={baseStyles.rowValue}>{system.primary_owner?.full_name || "Unassigned"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Deployment Regions</Text>
            <Text style={baseStyles.rowValue}>{formatList(system.deployment_regions)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Affected Groups</Text>
            <Text style={baseStyles.rowValue}>{formatList(system.affected_groups)}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Value Chain Role</Text>
            <Text style={baseStyles.rowValue}>{formatList(system.value_chain_role)}</Text>
          </View>
        </View>

        {/* Document Control */}
        <View style={baseStyles.sectionKeepTogether} wrap={false}>
          <Text style={baseStyles.sectionTitle}>Document Control</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Assessment Mode</Text>
            <Text style={baseStyles.rowValue}>{system.wizard_mode === "full" ? "Full Assessment" : "Quick Capture"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>System Created</Text>
            <Text style={baseStyles.rowValue}>{format(new Date(system.created_at), "PPP")}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Document Generated</Text>
            <Text style={baseStyles.rowValue}>{format(new Date(), "PPP 'at' HH:mm")}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Generated By</Text>
            <Text style={baseStyles.rowValue}>{generatedBy}</Text>
          </View>
        </View>

        {/* Disclaimer */}
        <View style={{ marginTop: 20, padding: 12, backgroundColor: colors.gray[50], borderRadius: 4 }} wrap={false}>
          <Text style={{ fontSize: 9, fontWeight: 600, marginBottom: 4, color: colors.gray[700] }}>
            Disclaimer
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[500], lineHeight: 1.4 }}>
            This document is generated based on information entered into the Klarvo platform. It is intended to support EU AI Act compliance efforts but does not constitute legal advice. Organizations should consult qualified legal counsel to ensure full compliance with applicable regulations.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
