import { Text, View } from "@react-pdf/renderer";
import { baseStyles, colors } from "@/lib/pdfStyles";

interface RunningHeaderProps {
  documentTitle: string;
  organizationName?: string;
}

/**
 * Running header component for consistent branding across all pages
 */
export function RunningHeader({ documentTitle, organizationName }: RunningHeaderProps) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>{documentTitle}</Text>
      {organizationName && (
        <Text style={baseStyles.runningHeaderOrg}>{organizationName}</Text>
      )}
    </View>
  );
}

interface RunningFooterProps {
  generatedDate: string;
  pageNumber?: number;
  totalPages?: number;
  confidential?: boolean;
}

/**
 * Running footer component with page numbers and confidentiality notice
 * Uses `fixed` prop to appear on all pages
 */
export function RunningFooter({ 
  generatedDate, 
  pageNumber, 
  totalPages,
  confidential = true 
}: RunningFooterProps) {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>
        Generated by Klarvo EU AI Act Compliance Hub
      </Text>
      {confidential && (
        <Text style={baseStyles.footerConfidential}>Confidential</Text>
      )}
      <Text style={baseStyles.footerPage}>
        {generatedDate}
      </Text>
    </View>
  );
}

interface PageFooterProps {
  documentTitle: string;
  pageNumber: number;
  totalPages?: number;
  generatedDate: string;
}

/**
 * Simple page footer (non-fixed) for specific pages
 */
export function PageFooter({ documentTitle, pageNumber, totalPages, generatedDate }: PageFooterProps) {
  return (
    <View style={{
      position: "absolute",
      bottom: 25,
      left: 50,
      right: 50,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.gray[200],
    }}>
      <Text style={{ fontSize: 8, color: colors.gray[400] }}>{documentTitle}</Text>
      <Text style={{ fontSize: 8, color: colors.gray[400] }}>
        Page {pageNumber}{totalPages ? ` of ${totalPages}` : ""}
      </Text>
    </View>
  );
}

interface BulletListProps {
  items: string[];
  color?: string;
}

/**
 * Bullet list component with proper styling
 */
export function BulletList({ items, color = colors.emerald }: BulletListProps) {
  return (
    <View style={baseStyles.bulletList}>
      {items.map((item, i) => (
        <View key={i} style={baseStyles.bulletItem}>
          <Text style={[baseStyles.bullet, { color }]}>•</Text>
          <Text style={baseStyles.bulletText}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

interface TableRowProps {
  cells: string[];
  isHeader?: boolean;
  isAlt?: boolean;
  wideCells?: number[]; // Indices of cells that should be wider
}

/**
 * Table row component with alternating backgrounds
 */
export function TableRow({ cells, isHeader = false, isAlt = false, wideCells = [] }: TableRowProps) {
  const rowStyle = isHeader 
    ? baseStyles.tableHeader 
    : isAlt 
      ? baseStyles.tableRowAlt 
      : baseStyles.tableRow;

  return (
    <View style={rowStyle} wrap={false}>
      {cells.map((cell, i) => {
        const cellStyle = isHeader
          ? wideCells.includes(i) ? baseStyles.tableHeaderCellWide : baseStyles.tableHeaderCell
          : wideCells.includes(i) ? baseStyles.tableCellWide : baseStyles.tableCell;
        
        return <Text key={i} style={cellStyle}>{cell}</Text>;
      })}
    </View>
  );
}

interface DataRowProps {
  label: string;
  value: string;
}

/**
 * Key-value row for displaying data
 */
export function DataRow({ label, value }: DataRowProps) {
  return (
    <View style={baseStyles.row}>
      <Text style={baseStyles.rowLabel}>{label}</Text>
      <Text style={baseStyles.rowValue}>{value}</Text>
    </View>
  );
}

interface InfoBoxProps {
  children: React.ReactNode;
  variant?: "info" | "warning" | "success" | "danger";
}

/**
 * Info box component for callouts
 */
export function InfoBox({ children, variant = "info" }: InfoBoxProps) {
  const boxStyle = {
    info: baseStyles.infoBox,
    warning: baseStyles.warningBox,
    success: baseStyles.successBox,
    danger: baseStyles.dangerBox,
  }[variant];

  const textStyle = {
    info: baseStyles.infoBoxText,
    warning: baseStyles.warningBoxText,
    success: baseStyles.successBoxText,
    danger: baseStyles.dangerBoxText,
  }[variant];

  return (
    <View style={boxStyle} wrap={false}>
      <Text style={textStyle}>{children}</Text>
    </View>
  );
}

interface CheckItemProps {
  text: string;
  passed: boolean;
}

/**
 * Checklist item with pass/fail indicator
 */
export function CheckItem({ text, passed }: CheckItemProps) {
  return (
    <View style={{ flexDirection: "row", marginBottom: 6, alignItems: "flex-start" }} wrap={false}>
      <Text style={{ 
        width: 20, 
        fontSize: 12, 
        color: passed ? colors.success : colors.danger,
        fontWeight: 700,
      }}>
        {passed ? "✓" : "✗"}
      </Text>
      <Text style={{ flex: 1, fontSize: 10, color: colors.gray[800] }}>{text}</Text>
    </View>
  );
}

interface SectionTitleProps {
  children: React.ReactNode;
  number?: string;
}

/**
 * Section title with optional numbering and orphan prevention
 */
export function SectionTitle({ children, number }: SectionTitleProps) {
  return (
    <Text style={baseStyles.sectionTitle}>
      {number && `${number}. `}{children}
    </Text>
  );
}

interface SignatureSectionProps {
  signers: Array<{
    role: string;
    name?: string;
    date?: string;
  }>;
}

/**
 * Signature section for document approval
 */
export function SignatureSection({ signers }: SignatureSectionProps) {
  return (
    <View style={baseStyles.signatureSection} wrap={false}>
      <Text style={[baseStyles.h2, { marginTop: 0, marginBottom: 15 }]}>Document Approval</Text>
      <View style={baseStyles.signatureRow}>
        {signers.map((signer, i) => (
          <View key={i} style={baseStyles.signatureBlock}>
            <View style={baseStyles.signatureLine} />
            <Text style={baseStyles.signatureLabel}>{signer.role}</Text>
            {signer.name && (
              <Text style={{ fontSize: 9, color: colors.gray[800], marginTop: 2 }}>
                {signer.name}
              </Text>
            )}
            {signer.date && (
              <Text style={{ fontSize: 8, color: colors.gray[500], marginTop: 2 }}>
                {signer.date}
              </Text>
            )}
          </View>
        ))}
      </View>
    </View>
  );
}

interface CoverPageMetaProps {
  items: Array<{ label: string; value: string }>;
}

/**
 * Cover page metadata display
 */
export function CoverPageMeta({ items }: CoverPageMetaProps) {
  return (
    <View style={{ marginTop: 20 }}>
      {items.map((item, i) => (
        <Text key={i} style={baseStyles.coverMeta}>
          <Text style={baseStyles.coverMetaLabel}>{item.label}: </Text>
          {item.value}
        </Text>
      ))}
    </View>
  );
}

interface TOCItemProps {
  section: string;
  page: string | number;
}

/**
 * Table of Contents item
 */
export function TOCItem({ section, page }: TOCItemProps) {
  return (
    <View style={baseStyles.tocItem}>
      <Text style={baseStyles.tocSection}>{section}</Text>
      <Text style={baseStyles.tocPage}>{page}</Text>
    </View>
  );
}
