import { Link } from "react-router-dom";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { CTASection } from "@/components/marketing/CTASection";
import { RelatedContent } from "@/components/marketing/RelatedContent";
import { HubNavigation } from "@/components/marketing/HubNavigation";
import { SEOHead, SchemaMarkup, createArticleSchema, createFAQSchema, createBreadcrumbSchema } from "@/components/seo";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  ArrowRight,
  MessageSquare,
  Image,
  Video,
  FileText,
  CheckCircle,
  AlertTriangle,
  Clock,
  Shield,
  Eye
} from "lucide-react";

const transparencyTypes = [
  {
    icon: MessageSquare,
    title: "AI Interaction Disclosure",
    obligation: "Inform people they are interacting with an AI system",
    who: "Deployers of AI systems that interact directly with people",
    when: "Before or at the first interaction",
    exception: "Not required if obvious from context that it's AI",
    example: "Chatbots must display 'You are chatting with an AI assistant'",
    deepDive: "This is the most common transparency obligation for SMEs. Any customer-facing AI—chatbots, virtual assistants, AI-powered support systems—must clearly inform users they're interacting with AI, not a human. The disclosure must be 'clear and distinguishable' and provided at the earliest opportunity. An exception exists when it's 'obvious' to a reasonably informed person—but don't assume your users will know. When in doubt, disclose.",
    implementationTips: [
      "Add a visible label or banner at the top of chat interfaces",
      "Include AI disclosure in welcome messages",
      "For voice AI, announce 'You are speaking with an AI assistant' before the conversation",
      "For email AI, include a footer: 'This response was generated by AI'",
    ]
  },
  {
    icon: Image,
    title: "Synthetic Content Marking",
    obligation: "Mark AI-generated content in a machine-readable format",
    who: "Providers of AI systems that generate synthetic content",
    when: "At the time of generation/output",
    exception: "Assistive functions, no substantial editing, or obvious AI nature",
    example: "AI image generator embeds metadata indicating AI creation",
    deepDive: "This obligation primarily falls on providers (the companies building AI tools), not deployers. However, deployers should understand it because you need to ensure your providers are meeting this obligation. If you use AI to generate images, audio, video, or text, check that the provider's system includes machine-readable marking (e.g., C2PA metadata for images). If you substantially edit AI-generated content, the marking obligation may transfer to you.",
    implementationTips: [
      "Ask your AI provider about machine-readable content marking",
      "Maintain records of which content is AI-generated",
      "If you publish AI-generated images, verify they contain provenance metadata",
      "For AI-generated text that you edit, document the AI's contribution",
    ]
  },
  {
    icon: Video,
    title: "Deepfake Disclosure",
    obligation: "Disclose that content has been artificially generated/manipulated",
    who: "Deployers who publish deepfakes",
    when: "At the point of publication/distribution",
    exception: "Creative/artistic works where disclosure would undermine the work",
    example: "Video with synthetic face swap must be labeled as manipulated",
    deepDive: "If you create or publish content where AI has been used to generate or manipulate images, audio, or video of existing persons, places, or events in a way that could be mistaken for authentic—you must disclose this. The disclosure must be made at the point of distribution, clearly and prominently. There's a narrow exception for artistic works, but this doesn't cover marketing, news, or informational content.",
    implementationTips: [
      "Add visible watermarks or labels to AI-manipulated media",
      "Include disclosures in video descriptions and thumbnails",
      "For audio content, add verbal disclosure at the beginning",
      "Keep records of all AI-generated/manipulated content published",
    ]
  },
  {
    icon: FileText,
    title: "AI-Generated Text Disclosure",
    obligation: "Disclose AI-generation for text on public interest matters",
    who: "Deployers publishing AI-generated text on public interest topics",
    when: "At the point of publication",
    exception: "When human editorial review exists and editor takes responsibility",
    example: "AI-written news summary must indicate AI involvement",
    deepDive: "This targets AI-generated text published to inform the public on matters of public interest—news articles, public health information, policy summaries, educational content. If AI generates or substantially shapes such text and you publish it, you must disclose the AI involvement. There's an important exception: if a human exercises editorial control and an identified entity takes editorial responsibility, disclosure may not be required. This recognises that human-edited AI drafts may not need labelling if the human is meaningfully reviewing and taking responsibility.",
    implementationTips: [
      "Add 'This article was drafted with AI assistance' to published content",
      "If using the editorial exception, document who reviewed and approved",
      "Maintain an internal register of AI-assisted publications",
      "Create a policy for when AI-generated content requires disclosure",
    ]
  },
];

const faqQuestions = [
  {
    question: "What is Article 50 of the EU AI Act?",
    answer: "Article 50 establishes transparency obligations for certain AI systems. It requires disclosures when people interact with AI, when AI generates synthetic content, for deepfakes, and for AI-generated text published on public interest matters. These are sometimes called 'limited risk' obligations."
  },
  {
    question: "When do Article 50 obligations apply?",
    answer: "Most Article 50 transparency obligations apply from 2 August 2026. However, organisations should prepare now to ensure systems and processes are ready—especially for chatbots and content generation tools already in use."
  },
  {
    question: "Who is responsible for Article 50 compliance?",
    answer: "Responsibilities are split: providers must enable transparency (e.g., machine-readable marking capabilities for synthetic content), while deployers must implement disclosures to end users (e.g., chatbot labels, deepfake notices). Both have obligations depending on the scenario."
  },
  {
    question: "What are the penalties for non-compliance?",
    answer: "Violations of transparency obligations can result in fines up to €15 million or 3% of annual worldwide turnover, whichever is higher. While lower than fines for prohibited practices (€35M/7%), they are still significant—especially for SMEs."
  },
  {
    question: "How should I implement AI interaction disclosure?",
    answer: "Disclosure should be clear, prominent, and provided before or at first interaction. Common approaches include chatbot welcome messages ('You are chatting with an AI assistant'), UI labels, voice announcements for phone systems, and email footers for AI-generated responses."
  },
  {
    question: "Do I need to disclose AI use in internal tools?",
    answer: "Article 50 transparency obligations primarily target interactions with natural persons who might not know they're dealing with AI. Internal tools used by your own staff are covered by AI literacy requirements (Article 4) rather than Article 50—your staff should know they're using AI through training, not disclosure labels."
  },
  {
    question: "What about AI-generated marketing content?",
    answer: "If AI generates marketing images, videos, or text, different obligations may apply. Synthetic images/video require machine-readable marking (provider obligation). Deepfake-style content requires visible disclosure. AI-generated text on public interest matters requires disclosure unless human editorial control exists. Standard marketing copy that isn't on 'public interest matters' may not trigger Article 50 text obligations."
  }
];

export default function Article50Guide() {
  const articleSchema = createArticleSchema({
    headline: "Article 50 Transparency Obligations: Complete Guide",
    description: "Comprehensive guide to EU AI Act Article 50 transparency requirements covering AI interaction disclosure, synthetic content marking, deepfake disclosure, and AI-generated text.",
    datePublished: "2025-01-15",
    dateModified: "2026-02-28",
    author: "Klarvo Compliance Team"
  });

  const faqSchema = createFAQSchema({ questions: faqQuestions });

  const breadcrumbSchema = createBreadcrumbSchema({
    items: [
      { name: "Home", url: "https://klarvo.io" },
      { name: "Guides", url: "https://klarvo.io/guides" },
      { name: "Article 50 Transparency", url: "https://klarvo.io/guides/article-50-transparency-obligations" }
    ]
  });

  return (
    <MarketingLayout>
      <SEOHead
        title="Article 50 Transparency Obligations - EU AI Act Guide"
        description="Complete guide to EU AI Act Article 50 transparency requirements. Learn about AI interaction disclosure, synthetic content marking, deepfake disclosure, and AI-generated text obligations."
        keywords={["Article 50", "AI transparency", "EU AI Act transparency", "synthetic content disclosure", "AI disclosure requirements", "deepfake disclosure"]}
        canonical="https://klarvo.io/guides/article-50-transparency-obligations"
      />
      <SchemaMarkup schema={[articleSchema, faqSchema, breadcrumbSchema]} />

      {/* Hero */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-4 mb-4">
              <Badge>Guide</Badge>
              <Badge variant="outline">Article 50</Badge>
              <div className="flex items-center text-sm text-muted-foreground">
                <Clock className="h-4 w-4 mr-1" />
                18 min read
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-6">
              Article 50 Transparency Obligations
            </h1>
            <p className="text-xl text-muted-foreground mb-8">
              The complete guide to EU AI Act transparency requirements. Understand when and how to disclose AI use to your users, customers, and the public—with implementation guidance and ready-to-use disclosure templates.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" asChild>
                <Link to="/tools/transparency-obligation-checker">
                  Check Your Obligations
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/templates/article-50-disclosure-templates">
                  Get Disclosure Templates
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Overview */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8">What is Article 50?</h2>
            <div className="prose prose-lg max-w-none">
              <p className="text-muted-foreground text-lg leading-relaxed mb-6">
                Article 50 of the EU AI Act establishes transparency obligations to ensure people know when they're interacting with AI or viewing AI-generated content. These requirements aim to protect fundamental rights and enable informed decision-making. Sometimes called "limited risk" obligations, they apply to a broader range of AI systems than the high-risk requirements—touching any AI that interacts with people or generates content.
              </p>
              <p className="text-muted-foreground leading-relaxed mb-6">
                For most SMEs, the AI interaction disclosure (chatbots, virtual assistants) and synthetic content marking (AI-generated images, text) are the most relevant. If you use AI in customer-facing roles, transparency obligations almost certainly apply to you—even if your systems aren't classified as high-risk.
              </p>
              <Card className="mb-8">
                <CardContent className="py-6">
                  <div className="flex items-start gap-4">
                    <AlertTriangle className="h-6 w-6 text-warning shrink-0 mt-1" />
                    <div>
                      <p className="font-medium mb-2">Key Timeline</p>
                      <p className="text-sm text-muted-foreground">
                        Most Article 50 obligations apply from <strong>2 August 2026</strong>. However, organisations should prepare now—especially those already using chatbots, AI content generation, or synthetic media. Implementing disclosure mechanisms takes time, and your customers may ask about your AI transparency posture before the deadline.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Four Types — expanded */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-4 text-center">The Four Transparency Scenarios</h2>
            <p className="text-lg text-muted-foreground text-center mb-12">
              Article 50 covers four distinct scenarios, each with different obligations, responsible parties, and implementation requirements.
            </p>
            <div className="space-y-8">
              {transparencyTypes.map((type, index) => (
                <Card key={index}>
                  <CardHeader>
                    <div className="flex items-center gap-4">
                      <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
                        <type.icon className="h-6 w-6 text-primary" />
                      </div>
                      <CardTitle className="text-xl">{type.title}</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid gap-4 md:grid-cols-2">
                      <div>
                        <p className="text-sm font-medium text-primary mb-1">Obligation</p>
                        <p className="text-sm text-muted-foreground">{type.obligation}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-primary mb-1">Who</p>
                        <p className="text-sm text-muted-foreground">{type.who}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-primary mb-1">When</p>
                        <p className="text-sm text-muted-foreground">{type.when}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-primary mb-1">Exception</p>
                        <p className="text-sm text-muted-foreground">{type.exception}</p>
                      </div>
                    </div>
                    <div className="p-4 bg-muted/50 rounded-lg">
                      <p className="text-sm font-medium mb-1">Example</p>
                      <p className="text-sm text-muted-foreground">{type.example}</p>
                    </div>
                    <div>
                      <p className="text-sm text-muted-foreground">{type.deepDive}</p>
                    </div>
                    <div>
                      <p className="text-sm font-medium mb-2">Implementation tips:</p>
                      <ul className="space-y-1">
                        {type.implementationTips.map((tip, i) => (
                          <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                            <CheckCircle className="h-3 w-3 text-primary shrink-0 mt-1" />
                            {tip}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Provider vs Deployer responsibilities */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">Provider vs Deployer: Who Does What?</h2>
            <div className="grid gap-6 md:grid-cols-2">
              <Card>
                <CardHeader>
                  <Shield className="h-8 w-8 text-primary mb-2" />
                  <CardTitle>Provider Responsibilities</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2 text-sm text-muted-foreground">
                  <p>• Build machine-readable marking capabilities into AI systems that generate synthetic content</p>
                  <p>• Provide technical documentation explaining marking methods</p>
                  <p>• Enable deployers to implement disclosures (e.g., API flags for AI-generated content)</p>
                  <p>• Keep marking technology up to date with evolving standards</p>
                </CardContent>
              </Card>
              <Card className="border-primary">
                <CardHeader>
                  <Eye className="h-8 w-8 text-primary mb-2" />
                  <CardTitle>Deployer Responsibilities (You)</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2 text-sm text-muted-foreground">
                  <p>• Implement AI interaction disclosures in customer-facing interfaces</p>
                  <p>• Inform people about emotion recognition or biometric categorisation</p>
                  <p>• Label deepfakes and AI-manipulated media before publication</p>
                  <p>• Disclose AI-generated text on public interest matters</p>
                  <p>• Keep evidence of all disclosures (screenshots, copy, configs)</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* What To Do Next */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">What To Do Next</h2>
            <div className="grid gap-6 md:grid-cols-2">
              <Card className="hover:border-primary transition-colors">
                <CardHeader>
                  <CheckCircle className="h-8 w-8 text-primary mb-2" />
                  <CardTitle className="text-lg">Check Your Obligations</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">Run our transparency checker to identify which Article 50 obligations apply to each of your AI systems.</p>
                  <Button asChild variant="link" className="p-0 h-auto">
                    <Link to="/tools/transparency-obligation-checker">Run Checker <ArrowRight className="ml-1 h-4 w-4" /></Link>
                  </Button>
                </CardContent>
              </Card>
              <Card className="hover:border-primary transition-colors">
                <CardHeader>
                  <FileText className="h-8 w-8 text-primary mb-2" />
                  <CardTitle className="text-lg">Get Disclosure Templates</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">Download ready-to-use disclosure copy for chatbots, AI-generated content, and synthetic media.</p>
                  <Button asChild variant="link" className="p-0 h-auto">
                    <Link to="/templates/article-50-disclosure-templates">Get Templates <ArrowRight className="ml-1 h-4 w-4" /></Link>
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4 max-w-3xl">
          <h2 className="text-3xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqQuestions.map((faq, index) => (
              <div key={index} className="bg-background rounded-lg p-6 shadow-sm">
                <h3 className="font-semibold text-lg mb-2">{faq.question}</h3>
                <p className="text-muted-foreground">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <RelatedContent currentHref="/guides/article-50-transparency-obligations" title="Related Resources" />

      <section className="py-8 container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <HubNavigation />
        </div>
      </section>

      <CTASection
        title="Track Your Transparency Compliance"
        subtitle="Klarvo identifies which AI systems need disclosures and helps you evidence compliance with screenshots, copy docs, and audit trails."
        primaryCta={{ label: "Start Free", href: "/auth/signup" }}
        secondaryCta={{ label: "See All Guides", href: "/guides" }}
        variant="gradient"
      />
    </MarketingLayout>
  );
}
