import { Link } from "react-router-dom";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { CTASection } from "@/components/marketing/CTASection";
import { SEOHead, SchemaMarkup, createArticleSchema, createFAQSchema, createBreadcrumbSchema } from "@/components/seo";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Clock, 
  ArrowRight,
  CheckCircle,
  Download,
  Users,
  Eye,
  Database,
  AlertTriangle,
  FileText,
  Bell
} from "lucide-react";

const obligations = [
  {
    icon: FileText,
    title: "Use According to Instructions",
    article: "Article 26(1)",
    description: "Deployers must use high-risk AI systems in accordance with the instructions of use accompanying the system.",
    whatToDo: [
      "Obtain the provider's instructions for use",
      "Create internal SOPs based on these instructions",
      "Train operators on correct usage",
      "Document adherence to instructions"
    ]
  },
  {
    icon: Users,
    title: "Human Oversight",
    article: "Article 26(2)",
    description: "Assign human oversight to persons who have the necessary competence, training, and authority.",
    whatToDo: [
      "Designate oversight owner for each system",
      "Document competence requirements",
      "Provide necessary training",
      "Grant authority to intervene and stop the system"
    ]
  },
  {
    icon: Database,
    title: "Input Data Management",
    article: "Article 26(4)",
    description: "Where deployers control input data, ensure it is relevant and sufficiently representative.",
    whatToDo: [
      "Document what input data you control",
      "Establish data quality checks",
      "Monitor for bias and representativeness",
      "Keep records of data quality measures"
    ]
  },
  {
    icon: Eye,
    title: "Monitoring",
    article: "Article 26(5)",
    description: "Monitor the operation of the high-risk AI system based on the instructions of use.",
    whatToDo: [
      "Create monitoring plan per provider instructions",
      "Establish KPIs and thresholds",
      "Schedule regular monitoring reviews",
      "Document monitoring activities"
    ]
  },
  {
    icon: AlertTriangle,
    title: "Risk Reporting & Suspension",
    article: "Article 26(5)",
    description: "Inform the provider/distributor and suspend use if you identify risks to health, safety, or fundamental rights.",
    whatToDo: [
      "Create escalation procedures",
      "Define suspension criteria",
      "Establish provider communication channels",
      "Document incidents and responses"
    ]
  },
  {
    icon: Bell,
    title: "Serious Incident Reporting",
    article: "Article 26(5)",
    description: "Report serious incidents to the provider and relevant market surveillance authorities.",
    whatToDo: [
      "Define what constitutes a serious incident",
      "Create incident reporting procedures",
      "Identify relevant authorities",
      "Keep incident records"
    ]
  },
  {
    icon: Database,
    title: "Log Retention",
    article: "Article 26(6)",
    description: "Keep logs automatically generated by the AI system under your control for at least 6 months.",
    whatToDo: [
      "Identify what logs are generated",
      "Ensure 6-month minimum retention",
      "Establish access controls",
      "Enable log export capability"
    ]
  },
  {
    icon: Users,
    title: "Workplace Notification",
    article: "Article 26(7)",
    description: "If you're an employer using high-risk AI in the workplace, inform workers and their representatives.",
    whatToDo: [
      "Identify workplace AI uses",
      "Draft worker notification",
      "Communicate before deployment",
      "Document notification"
    ]
  },
];

const faqQuestions = [
  {
    question: "Who is a 'deployer' under the EU AI Act?",
    answer: "A deployer is any natural or legal person, public authority, agency, or other body using an AI system under its authority, except where the AI system is used in the course of a personal non-professional activity."
  },
  {
    question: "When do Article 26 obligations apply?",
    answer: "Article 26 obligations apply to deployers of high-risk AI systems. Most Article 26 obligations will apply from 2 August 2026, though you should prepare now."
  },
  {
    question: "What's the difference between provider and deployer obligations?",
    answer: "Providers (developers/manufacturers) have obligations around design, documentation, and conformity. Deployers (users) have obligations around use, oversight, monitoring, and incidents."
  },
  {
    question: "Do I need to do a FRIA as a deployer?",
    answer: "FRIA (Fundamental Rights Impact Assessment) is required for certain deployers—specifically public bodies and some private entities providing public services—before deploying certain high-risk AI systems."
  }
];

export default function Article26Guide() {
  const articleSchema = createArticleSchema({
    headline: "Article 26 Deployer Obligations: Operational Playbook",
    description: "Complete guide to EU AI Act Article 26 deployer obligations for high-risk AI systems. Covers oversight, monitoring, logs, incidents, and workplace notification.",
    datePublished: "2025-01-20",
    dateModified: "2025-01-31"
  });

  const faqSchema = createFAQSchema({ questions: faqQuestions });

  const breadcrumbSchema = createBreadcrumbSchema({
    items: [
      { name: "Home", url: "https://klarvo.io" },
      { name: "Guides", url: "https://klarvo.io/guides" },
      { name: "Article 26 Deployer Obligations", url: "https://klarvo.io/guides/article-26-deployer-obligations" }
    ]
  });

  return (
    <MarketingLayout>
      <SEOHead
        title="Article 26 Deployer Obligations - EU AI Act Guide"
        description="Complete guide to Article 26 deployer obligations for high-risk AI systems. Covers human oversight, monitoring, log retention, incident reporting, and worker notification."
        keywords={["Article 26 EU AI Act", "deployer obligations", "high-risk AI obligations", "AI deployer requirements", "EU AI Act deployer"]}
        canonical="https://klarvo.io/guides/article-26-deployer-obligations"
        ogType="article"
      />
      <SchemaMarkup schema={[articleSchema, faqSchema, breadcrumbSchema]} />

      {/* Hero */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-4 mb-6">
              <Badge>Guide</Badge>
              <Badge variant="destructive">High-Risk</Badge>
              <div className="flex items-center text-sm text-muted-foreground">
                <Clock className="h-4 w-4 mr-1" />
                15 min read
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-6">
              Article 26 Deployer Obligations
            </h1>
            <p className="text-xl text-muted-foreground mb-8">
              The operational playbook for deployers of high-risk AI systems. What you must do, who owns it, and what evidence you need.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" asChild>
                <Link to="/templates/article-26-checklist">
                  <Download className="mr-2 h-5 w-5" />
                  Get Article 26 Checklist
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/tools/high-risk-checker-annex-iii">
                  Check if High-Risk
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Obligations */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-3xl font-bold mb-4 text-center">The 8 Deployer Obligations</h2>
            <p className="text-lg text-muted-foreground text-center mb-12">
              Article 26 sets out specific requirements for anyone deploying high-risk AI systems.
            </p>
            <div className="space-y-8">
              {obligations.map((obligation, index) => (
                <Card key={index}>
                  <CardHeader>
                    <div className="flex items-start gap-4">
                      <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                        <obligation.icon className="h-6 w-6 text-primary" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <CardTitle className="text-xl">{obligation.title}</CardTitle>
                          <Badge variant="outline">{obligation.article}</Badge>
                        </div>
                        <p className="text-muted-foreground">{obligation.description}</p>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <h4 className="font-semibold mb-3">What to do:</h4>
                    <ul className="grid gap-2 md:grid-cols-2">
                      {obligation.whatToDo.map((item, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm">
                          <CheckCircle className="h-4 w-4 text-success shrink-0 mt-0.5" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4 max-w-3xl">
          <h2 className="text-3xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqQuestions.map((faq, index) => (
              <div key={index} className="bg-background rounded-lg p-6 shadow-sm">
                <h3 className="font-semibold text-lg mb-2">{faq.question}</h3>
                <p className="text-muted-foreground">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <CTASection
        title="Automate Your Article 26 Compliance"
        subtitle="Klarvo auto-generates deployer checklists and tracks evidence for each obligation."
        primaryCta={{ label: "Start Free", href: "/auth/signup" }}
        secondaryCta={{ label: "See All Guides", href: "/guides" }}
        variant="gradient"
      />
    </MarketingLayout>
  );
}
