import { Link } from "react-router-dom";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { CTASection } from "@/components/marketing/CTASection";
import { RelatedContent } from "@/components/marketing/RelatedContent";
import { HubNavigation } from "@/components/marketing/HubNavigation";
import { SEOHead, SchemaMarkup, createArticleSchema, createFAQSchema, createBreadcrumbSchema } from "@/components/seo";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  ArrowRight,
  XCircle,
  AlertTriangle,
  Shield,
  Clock,
  CheckCircle,
  FileText,
  Scale
} from "lucide-react";

const prohibitedPractices = [
  {
    title: "Harmful Manipulation/Deception",
    article: "5(1)(a)",
    description: "AI systems using subliminal, manipulative, or deceptive techniques that distort behavior and cause significant harm.",
    deepDive: "This prohibition targets AI that operates 'below the threshold of consciousness' or uses deliberate deception to alter someone's behaviour in ways they didn't intend or wouldn't agree to. The key word is 'significant harm'—minor annoyances don't qualify. The harm must be actual or reasonably foreseeable, and the distortion of behaviour must be material, not trivial.",
    examples: ["Dark patterns designed to manipulate purchasing decisions causing financial harm", "Systems exploiting cognitive biases to influence political views harmfully", "AI-generated personalised pressure tactics targeting specific psychological vulnerabilities"],
    notCovered: ["Standard marketing personalization", "Transparent recommendation systems", "A/B testing that doesn't exploit psychological vulnerabilities"],
    practicalExample: "If your e-commerce chatbot uses urgency-based pressure ('Only 1 left! Buy NOW!') with fabricated scarcity data generated by AI, this could fall under manipulation. If the scarcity data is real and presented transparently, it's standard marketing."
  },
  {
    title: "Exploitation of Vulnerabilities",
    article: "5(1)(b)",
    description: "AI exploiting vulnerabilities due to age, disability, or social/economic situation causing significant harm.",
    deepDive: "This prohibition focuses on AI systems that take advantage of people who are less able to protect themselves. The vulnerability must be linked to age (children, elderly), disability (cognitive, physical), or socio-economic situation (financial distress, low digital literacy). The exploitation must cause or be likely to cause significant harm—financial, physical, or psychological.",
    examples: ["Predatory lending AI targeting financially distressed individuals", "Gambling AI targeting addiction-prone users", "AI toy companions manipulating children's behaviour for commercial purposes"],
    notCovered: ["Accessibility features for disabled users", "Age-appropriate content filtering", "Financial assistance tools designed to help vulnerable groups"],
    practicalExample: "A buy-now-pay-later AI that specifically targets users with indicators of financial distress (late payments, overdraft usage) with aggressive credit offers could be exploitative. The same tool offered transparently with responsible lending checks would not."
  },
  {
    title: "Social Scoring",
    article: "5(1)(c)",
    description: "Evaluating/classifying people based on social behavior for unrelated decisions leading to detrimental treatment.",
    deepDive: "Social scoring is prohibited when it classifies people based on their social behaviour or personal characteristics, and then uses that classification to make decisions in unrelated contexts—leading to treatment that is unjustified or disproportionate. The key elements are: (1) the scoring relates to social behaviour, (2) the decision context is unrelated to the original data collection, and (3) the result is detrimental or disproportionate.",
    examples: ["Denying insurance based on social media activity", "Employment decisions based on personal lifestyle choices", "Restricting access to public services based on 'trustworthiness' scores derived from unrelated behaviour"],
    notCovered: ["Credit scoring based on financial history", "Background checks for relevant roles", "Fraud detection based on transaction patterns"],
    practicalExample: "If your HR AI screens candidates' social media posts about political views or lifestyle choices and factors this into hiring scores—that's social scoring. Using professional history from LinkedIn to assess relevant experience is standard recruitment."
  },
  {
    title: "Criminal Risk Profiling",
    article: "5(1)(d)",
    description: "Predicting criminal offense risk based solely on profiling or personality traits (not actual criminal behavior).",
    deepDive: "This targets predictive policing and pre-crime AI that assesses an individual's likelihood of committing a criminal offence based on their profile (demographics, personality traits, social characteristics) rather than actual criminal behaviour or involvement in criminal activity. The word 'solely' is important—if the assessment combines profiling with objective evidence of criminal conduct, it may not be prohibited.",
    examples: ["Pre-crime prediction based on demographics", "Risk scoring based purely on personality assessments", "Neighbourhood-level crime prediction that identifies individuals"],
    notCovered: ["Recidivism assessment based on criminal history", "Evidence-based risk assessment in justice", "Statistical crime hotspot mapping (without individual identification)"],
    practicalExample: "Most SMEs won't encounter this prohibition directly. However, if you use AI-powered security tools that flag 'suspicious' individuals based on appearance or demographic profiles rather than behaviour, you should review whether this crosses the line."
  },
  {
    title: "Facial Recognition Database Scraping",
    article: "5(1)(e)",
    description: "Creating/expanding facial recognition databases through untargeted scraping of images from internet or CCTV.",
    deepDive: "This prohibits building facial recognition databases by mass-collecting images without specific consent or authorisation. The prohibition covers both internet scraping (social media, websites) and CCTV footage collection. 'Untargeted' is the key word—targeted collection with proper authorisation for specific purposes is not covered.",
    examples: ["Scraping social media for facial recognition training", "Mass CCTV capture for identity databases", "Crawling publicly available photos to build biometric databases"],
    notCovered: ["User-uploaded photos with consent", "Targeted law enforcement with warrants", "ID verification with explicit user consent"],
    practicalExample: "If your security vendor's facial recognition system was trained on scraped internet images (like Clearview AI's model), using that system could implicate you. Ask your vendor about their training data sources as part of vendor due diligence."
  },
  {
    title: "Workplace/Education Emotion Inference",
    article: "5(1)(f)",
    description: "Inferring emotions in workplace or educational settings (with limited medical/safety exceptions).",
    deepDive: "This prohibition specifically targets AI systems that attempt to recognise or infer the emotional state of people in two contexts: workplaces and educational institutions. There are narrow exceptions for medical purposes (e.g., detecting pain in patients who cannot communicate) and safety purposes (e.g., driver fatigue detection in transport). Outside these exceptions, emotion recognition in these settings is banned—even if the data is collected 'for wellbeing purposes.'",
    examples: ["Monitoring employee emotions during meetings", "Assessing student engagement via emotional analysis", "Using webcam-based attention tracking during remote work"],
    notCovered: ["Medical emotion detection for safety", "Driver fatigue detection for transport safety", "Voluntary wellbeing check-ins without AI inference"],
    practicalExample: "If your video conferencing tool includes 'engagement scoring' or 'attention tracking' features that infer participant emotions during work meetings—turn this feature off. Even if marketed as 'productivity insights,' it likely constitutes prohibited emotion inference in a workplace context."
  },
  {
    title: "Sensitive Biometric Categorisation",
    article: "5(1)(g)",
    description: "Categorising people based on biometric data to infer protected characteristics.",
    deepDive: "This prohibits using biometric data (facial features, voice, gait, etc.) to categorise people into groups based on sensitive/protected characteristics: race, ethnicity, political opinions, trade union membership, religious or philosophical beliefs, sex life, or sexual orientation. The prohibition applies regardless of accuracy—even unreliable systems are banned because the attempt itself is considered harmful.",
    examples: ["Determining race or religion from facial features", "Inferring sexual orientation from biometric analysis", "Categorising political orientation from voice patterns"],
    notCovered: ["Age verification for content access", "Gender-neutral health diagnostics", "Accessibility adaptations based on disability detection with consent"],
    practicalExample: "If your customer analytics tool claims to infer customers' ethnicity, religion, or political leanings from profile photos or voice recordings—this is prohibited regardless of whether it's accurate. Remove any such features immediately."
  },
  {
    title: "Real-time Remote Biometric ID",
    article: "5(1)(h)",
    description: "Real-time remote biometric identification in public spaces for law enforcement (with narrow exceptions).",
    deepDive: "This is the most debated prohibition. It bans real-time remote biometric identification (primarily facial recognition) in publicly accessible spaces when used for law enforcement purposes. There are narrow exceptions for: searching for victims of specific crimes (kidnapping, trafficking), preventing specific imminent threats to life or terrorist attacks, and locating suspects of serious crimes listed in a specific framework decision. Even these exceptions require prior judicial authorisation in most cases.",
    examples: ["Mass surveillance facial recognition in city centers", "Real-time identification at public events", "Continuous biometric monitoring of public transport"],
    notCovered: ["Post-event investigation with authorization", "Border control with appropriate safeguards", "Access control in private premises with consent"],
    practicalExample: "This prohibition primarily affects law enforcement and public authorities. For SMEs, ensure your physical security systems (CCTV with facial recognition) don't operate as real-time biometric identification in publicly accessible areas."
  },
];

const faqQuestions = [
  {
    question: "When did prohibited practice rules apply?",
    answer: "Prohibited practice rules applied from 2 February 2025, making this one of the earliest enforcement dates in the EU AI Act. Organizations should have already ceased any prohibited uses."
  },
  {
    question: "What are the penalties for prohibited practices?",
    answer: "Violations of prohibited practices face the highest penalties under the AI Act: up to €35 million or 7% of annual worldwide turnover, whichever is higher. For SMEs, the penalty is the lower of these amounts."
  },
  {
    question: "How do I know if my AI system is prohibited?",
    answer: "Use our prohibited practices screening tool to check your systems against all 8 categories. If any indicators are found, stop using the system immediately and seek legal advice. When in doubt, err on the side of caution and document your reasoning."
  },
  {
    question: "Are there any exceptions to prohibited practices?",
    answer: "Some narrow exceptions exist, particularly for law enforcement uses under strict conditions (judicial authorisation, specific threat scenarios). Medical and safety exceptions exist for emotion inference. However, these are very limited and typically don't apply to commercial SME use cases."
  },
  {
    question: "What if I'm 'unsure' whether a practice is prohibited?",
    answer: "Document your uncertainty with a detailed rationale. Create a task for legal review. In the meantime, consider suspending the AI system's use until you have a clear conclusion. Klarvo's wizard includes a 'needs legal review' option that creates a blocking task and prevents classification from proceeding."
  },
  {
    question: "Do prohibited practice rules apply to AI I buy from vendors?",
    answer: "Yes. As a deployer, you are responsible for ensuring the AI systems you use don't constitute prohibited practices. If your vendor's tool performs a prohibited function—even if they marketed it as compliant—you bear responsibility for using it. This is why vendor due diligence matters."
  },
  {
    question: "How should I screen my AI systems for prohibited practices?",
    answer: "Screen each AI system against all 8 prohibited categories. For each, answer: does this system use manipulation/deception? Does it exploit vulnerable groups? Does it perform social scoring? Continue through all 8 checks. Document the screening result with reviewer sign-off. Klarvo's intake wizard includes this screening as Step 8 with all 8 questions."
  }
];

export default function ProhibitedPracticesGuide() {
  const articleSchema = createArticleSchema({
    headline: "Prohibited AI Practices (Article 5): Complete Guide",
    description: "Comprehensive guide to EU AI Act Article 5 prohibited practices. Understand the 8 banned AI uses including manipulation, social scoring, and biometric identification.",
    datePublished: "2025-01-10",
    dateModified: "2026-02-28",
    author: "Klarvo Compliance Team"
  });

  const faqSchema = createFAQSchema({ questions: faqQuestions });

  const breadcrumbSchema = createBreadcrumbSchema({
    items: [
      { name: "Home", url: "https://klarvo.io" },
      { name: "Guides", url: "https://klarvo.io/guides" },
      { name: "Prohibited Practices", url: "https://klarvo.io/guides/prohibited-ai-practices-article-5" }
    ]
  });

  return (
    <MarketingLayout>
      <SEOHead
        title="Prohibited AI Practices (Article 5) - EU AI Act Guide"
        description="Complete guide to EU AI Act Article 5 prohibited practices. Learn about the 8 banned AI uses: manipulation, social scoring, criminal profiling, biometric identification, and more."
        keywords={["prohibited AI practices", "Article 5", "banned AI", "EU AI Act prohibited", "social scoring", "biometric identification", "AI manipulation"]}
        canonical="https://klarvo.io/guides/prohibited-ai-practices-article-5"
      />
      <SchemaMarkup schema={[articleSchema, faqSchema, breadcrumbSchema]} />

      {/* Hero */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-2 mb-4">
              <Badge variant="destructive">Critical</Badge>
              <Badge variant="outline">Article 5</Badge>
              <div className="flex items-center text-sm text-muted-foreground">
                <Clock className="h-4 w-4 mr-1" />
                20 min read
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-6">
              Prohibited AI Practices (Article 5)
            </h1>
            <p className="text-xl text-muted-foreground mb-8">
              The EU AI Act bans 8 categories of AI practices outright. These rules applied from 2 February 2025 and carry the highest penalties—up to €35 million or 7% of global turnover. Here's what's banned, with practical examples for every category.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" asChild>
                <Link to="/tools/prohibited-practices-screening">
                  Screen Your AI Systems
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <a href="https://app.klarvo.io/auth/signup">
                  Document Compliance
                </a>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Warning */}
      <section className="py-8">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <Card className="border-destructive bg-destructive/5">
              <CardContent className="py-6">
                <div className="flex items-start gap-4">
                  <AlertTriangle className="h-8 w-8 text-destructive shrink-0" />
                  <div>
                    <h3 className="text-xl font-bold mb-2">These Rules Apply Now</h3>
                    <p className="text-muted-foreground mb-4">
                      Prohibited practice rules applied from <strong>2 February 2025</strong>. If you're using AI systems that fall into these categories, you must stop immediately. Penalties can reach €35 million or 7% of global turnover—the highest tier in the AI Act.
                    </p>
                    <p className="text-sm text-muted-foreground">
                      Even if you haven't formally screened your AI systems yet, ignorance is not a defence. Run the screening now and document your results. If any indicators are flagged, suspend the system and seek legal advice before continuing.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Why This Matters for SMEs */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-6">Why This Matters for Your Business</h2>
            <div className="prose max-w-none">
              <p className="text-lg text-muted-foreground mb-4">
                Most SMEs assume prohibited practices don't apply to them—"we're not doing social scoring or mass surveillance." But the reality is more nuanced. Many commonly used AI tools have features that could edge into prohibited territory if used carelessly. Consider these scenarios:
              </p>
              <div className="space-y-4 mb-8">
                <div className="p-4 bg-muted/30 rounded-lg">
                  <p className="font-semibold mb-1">Your video conferencing tool has "engagement scoring"</p>
                  <p className="text-sm text-muted-foreground">If it infers employee emotions during meetings, that's prohibited workplace emotion inference under Article 5(1)(f). Turn the feature off.</p>
                </div>
                <div className="p-4 bg-muted/30 rounded-lg">
                  <p className="font-semibold mb-1">Your marketing AI uses "psychographic targeting"</p>
                  <p className="text-sm text-muted-foreground">If it exploits cognitive vulnerabilities to manipulate behaviour causing harm, it could fall under Article 5(1)(a). Review how the targeting works.</p>
                </div>
                <div className="p-4 bg-muted/30 rounded-lg">
                  <p className="font-semibold mb-1">Your HR tool screens social media profiles</p>
                  <p className="text-sm text-muted-foreground">If it scores candidates based on lifestyle choices unrelated to the job, that's social scoring under Article 5(1)(c). Review the screening criteria.</p>
                </div>
              </div>
              <p className="text-muted-foreground">
                The solution isn't panic—it's systematic screening. Run each AI system through all 8 prohibited categories, document the results with a reviewer sign-off, and create a clear record. If everything passes, you have evidence. If something flags, you have a clear escalation path.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Practices */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8">The 8 Prohibited Practices — In Depth</h2>
            <p className="text-lg text-muted-foreground mb-12">
              For each prohibited practice, we explain the regulatory text, what it means in practice, and give real-world examples to help you assess your AI systems.
            </p>
            <div className="space-y-8">
              {prohibitedPractices.map((practice, index) => (
                <Card key={index}>
                  <CardHeader>
                    <div className="flex items-start gap-4">
                      <div className="h-10 w-10 rounded-full bg-destructive/10 flex items-center justify-center shrink-0">
                        <XCircle className="h-5 w-5 text-destructive" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <CardTitle className="text-lg">{practice.title}</CardTitle>
                          <Badge variant="outline" className="text-xs">Art. {practice.article}</Badge>
                        </div>
                        <p className="text-muted-foreground">{practice.description}</p>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="ml-14 space-y-4">
                    <div>
                      <p className="text-sm text-muted-foreground">{practice.deepDive}</p>
                    </div>
                    <div className="grid gap-4 md:grid-cols-2">
                      <div>
                        <p className="text-sm font-medium text-destructive mb-2">Prohibited examples:</p>
                        <ul className="space-y-1">
                          {practice.examples.map((ex, i) => (
                            <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                              <XCircle className="h-3 w-3 text-destructive shrink-0 mt-1" />
                              {ex}
                            </li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-success mb-2">Not covered (likely OK):</p>
                        <ul className="space-y-1">
                          {practice.notCovered.map((ex, i) => (
                            <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                              <Shield className="h-3 w-3 text-success shrink-0 mt-1" />
                              {ex}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                    <div className="p-4 bg-muted/50 rounded-lg">
                      <p className="text-sm font-medium mb-1">Practical example for SMEs:</p>
                      <p className="text-sm text-muted-foreground">{practice.practicalExample}</p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* How to Screen */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">How to Screen Your AI Systems</h2>
            <div className="space-y-4">
              <div className="flex gap-4 p-4 bg-muted/30 rounded-lg">
                <div className="h-10 w-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold shrink-0">1</div>
                <div>
                  <h3 className="font-semibold">List all AI systems</h3>
                  <p className="text-sm text-muted-foreground">Start from your <Link to="/guides/ai-inventory-eu-ai-act" className="text-primary hover:underline">AI inventory</Link>. If you don't have one, build one first—you can't screen what you haven't identified.</p>
                </div>
              </div>
              <div className="flex gap-4 p-4 bg-muted/30 rounded-lg">
                <div className="h-10 w-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold shrink-0">2</div>
                <div>
                  <h3 className="font-semibold">Run each through 8 checks</h3>
                  <p className="text-sm text-muted-foreground">For each AI system, answer yes/no/unsure to all 8 prohibited practice categories. Use our <Link to="/tools/prohibited-practices-screening" className="text-primary hover:underline">screening tool</Link> or the questions built into Klarvo's intake wizard (Step 8).</p>
                </div>
              </div>
              <div className="flex gap-4 p-4 bg-muted/30 rounded-lg">
                <div className="h-10 w-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold shrink-0">3</div>
                <div>
                  <h3 className="font-semibold">Document the result with sign-off</h3>
                  <p className="text-sm text-muted-foreground">Record the screening conclusion: "No prohibited indicators found" or "Potential prohibited practice—stop and escalate." Include reviewer name and date. Klarvo generates a classification memo with this section automatically.</p>
                </div>
              </div>
              <div className="flex gap-4 p-4 bg-muted/30 rounded-lg">
                <div className="h-10 w-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold shrink-0">4</div>
                <div>
                  <h3 className="font-semibold">Escalate any "unsure" answers</h3>
                  <p className="text-sm text-muted-foreground">If any answer is "unsure," create a legal review task. In Klarvo, this locks the classification to "Blocked" until the legal review is completed and documented.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* What To Do Next */}
      <section className="py-16 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">What To Do Next</h2>
            <div className="grid gap-6 md:grid-cols-2">
              <Card className="hover:border-primary transition-colors">
                <CardHeader>
                  <Shield className="h-8 w-8 text-primary mb-2" />
                  <CardTitle className="text-lg">Screen Your Systems</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">
                    Use our free screening tool to check each AI system against all 8 prohibited categories with guided questions.
                  </p>
                  <Button asChild variant="link" className="p-0 h-auto">
                    <Link to="/tools/prohibited-practices-screening">
                      Run Screening <ArrowRight className="ml-1 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
              <Card className="hover:border-primary transition-colors">
                <CardHeader>
                  <FileText className="h-8 w-8 text-primary mb-2" />
                  <CardTitle className="text-lg">Build Your Inventory</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">
                    Can't screen what you don't know about. Start with our AI inventory template or software.
                  </p>
                  <Button asChild variant="link" className="p-0 h-auto">
                    <Link to="/templates/ai-inventory-template">
                      Get Template <ArrowRight className="ml-1 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
              <Card className="hover:border-primary transition-colors">
                <CardHeader>
                  <Scale className="h-8 w-8 text-primary mb-2" />
                  <CardTitle className="text-lg">Classify Risk Levels</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">
                    After prohibited screening, check if your systems are high-risk under Annex III.
                  </p>
                  <Button asChild variant="link" className="p-0 h-auto">
                    <Link to="/guides/high-risk-ai-annex-iii">
                      Read High-Risk Guide <ArrowRight className="ml-1 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
              <Card className="hover:border-primary transition-colors">
                <CardHeader>
                  <CheckCircle className="h-8 w-8 text-primary mb-2" />
                  <CardTitle className="text-lg">Check AI Literacy</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground mb-4">
                    AI literacy (Article 4) also applies now. Ensure staff understand what's prohibited.
                  </p>
                  <Button asChild variant="link" className="p-0 h-auto">
                    <Link to="/guides/ai-literacy-article-4">
                      Read Literacy Guide <ArrowRight className="ml-1 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-16">
        <div className="container mx-auto px-4 max-w-3xl">
          <h2 className="text-3xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqQuestions.map((faq, index) => (
              <div key={index} className="bg-muted/30 rounded-lg p-6">
                <h3 className="font-semibold text-lg mb-2">{faq.question}</h3>
                <p className="text-muted-foreground">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <RelatedContent currentHref="/guides/prohibited-ai-practices-article-5" title="Related Resources" />

      <section className="py-8 container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <HubNavigation />
        </div>
      </section>

      <CTASection
        title="Screen Your AI Systems Now"
        subtitle="Use our free screening tool to check for prohibited practices and document your compliance."
        primaryCta={{ label: "Run Screening", href: "/tools/prohibited-practices-screening" }}
        secondaryCta={{ label: "See All Guides", href: "/guides" }}
        variant="gradient"
      />
    </MarketingLayout>
  );
}
