import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors, formatYesNoUnsure } from "@/lib/pdfStyles";

const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  checklistItem: {
    flexDirection: "row",
    marginBottom: 6,
    alignItems: "flex-start",
  },
  checkMark: {
    width: 18,
    fontSize: 11,
    fontWeight: 700,
  },
  checkComplete: {
    color: colors.success,
  },
  checkIncomplete: {
    color: colors.danger,
  },
  checkPartial: {
    color: colors.warning,
  },
  checkText: {
    flex: 1,
    fontSize: 9,
    color: colors.gray[800],
  },
});

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>Annex IV Technical Documentation — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer
function RunningFooter({ generatedDate }: { generatedDate: string }) {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

interface CheckItemProps {
  text: string;
  status: "complete" | "incomplete" | "partial";
}

function CheckItem({ text, status }: CheckItemProps) {
  const mark = status === "complete" ? "✓" : status === "partial" ? "○" : "✗";
  const markStyle = status === "complete" 
    ? styles.checkComplete 
    : status === "partial" 
      ? styles.checkPartial 
      : styles.checkIncomplete;

  return (
    <View style={styles.checklistItem} wrap={false}>
      <Text style={[styles.checkMark, markStyle]}>{mark}</Text>
      <Text style={styles.checkText}>{text}</Text>
    </View>
  );
}

export interface TechnicalDocumentation {
  id: string;
  ai_system_version_id: string;
  general_description?: string | null;
  intended_purpose?: string | null;
  design_specifications?: string | null;
  development_process?: string | null;
  monitoring_functioning?: string | null;
  risk_management_measures?: string | null;
  changes_modifications?: string | null;
  validation_testing?: string | null;
  cybersecurity_measures?: string | null;
  accuracy_metrics?: string | null;
  human_oversight_measures?: string | null;
  expected_lifetime?: string | null;
  created_at: string;
  updated_at: string;
}

export interface RiskRecord {
  id: string;
  hazard: string;
  hazard_category: string;
  severity: string;
  likelihood: string;
  risk_level: string;
  status: string;
  mitigation_measures?: string | null;
}

export interface Dataset {
  id: string;
  name: string;
  purpose?: string | null;
  data_quality_verified?: boolean | null;
  bias_checks_performed?: unknown | null;
}

interface AnnexIVTechDocsPDFProps {
  techDocs: TechnicalDocumentation | null;
  riskRecords: RiskRecord[];
  datasets: Dataset[];
  systemName: string;
  versionLabel: string;
  organizationName: string;
  generatedBy?: string;
}

export function AnnexIVTechDocsPDF({
  techDocs,
  riskRecords,
  datasets,
  systemName,
  versionLabel,
  organizationName,
  generatedBy,
}: AnnexIVTechDocsPDFProps) {
  const generatedDate = format(new Date(), "PPP");

  const getFieldStatus = (value: string | null | undefined): "complete" | "incomplete" | "partial" => {
    if (!value) return "incomplete";
    if (value.length < 50) return "partial";
    return "complete";
  };

  const annexIVSections = [
    { key: "general_description", label: "1. General description of the AI system", value: techDocs?.general_description },
    { key: "intended_purpose", label: "2. Intended purpose and foreseeable misuse", value: techDocs?.intended_purpose },
    { key: "design_specifications", label: "3. Design specifications and architecture", value: techDocs?.design_specifications },
    { key: "development_process", label: "4. Development process and tools", value: techDocs?.development_process },
    { key: "monitoring_functioning", label: "5. Monitoring, functioning, and control", value: techDocs?.monitoring_functioning },
    { key: "risk_management_measures", label: "6. Risk management measures", value: techDocs?.risk_management_measures },
    { key: "changes_modifications", label: "7. Changes and modifications", value: techDocs?.changes_modifications },
    { key: "validation_testing", label: "8. Validation and testing procedures", value: techDocs?.validation_testing },
    { key: "cybersecurity_measures", label: "9. Cybersecurity measures", value: techDocs?.cybersecurity_measures },
    { key: "accuracy_metrics", label: "10. Accuracy, robustness, and cybersecurity metrics", value: techDocs?.accuracy_metrics },
    { key: "human_oversight_measures", label: "11. Human oversight measures", value: techDocs?.human_oversight_measures },
    { key: "expected_lifetime", label: "12. Expected lifetime and maintenance", value: techDocs?.expected_lifetime },
  ];

  const completedSections = annexIVSections.filter(s => getFieldStatus(s.value) === "complete").length;
  const partialSections = annexIVSections.filter(s => getFieldStatus(s.value) === "partial").length;
  const completionPercent = Math.round(((completedSections + partialSections * 0.5) / annexIVSections.length) * 100);

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={baseStyles.coverPage}>
        <View>
          <Text style={baseStyles.coverBadge}>EU AI ACT — ARTICLE 11</Text>
          <Text style={baseStyles.coverTitle}>Technical Documentation</Text>
          <Text style={baseStyles.coverSubtitle}>Annex IV Structured Report</Text>
          <Text style={baseStyles.coverSystemName}>{systemName}</Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Version: </Text>{versionLabel}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Organization: </Text>{organizationName}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Generated: </Text>{generatedDate}
          </Text>
          {generatedBy && (
            <Text style={baseStyles.coverMeta}>
              <Text style={baseStyles.coverMetaLabel}>Generated By: </Text>{generatedBy}
            </Text>
          )}
        </View>

        <View style={baseStyles.coverFooter}>
          <Text style={{ fontSize: 10, color: colors.gray[500], marginBottom: 4 }}>
            Completion: {completionPercent}% ({completedSections} complete, {partialSections} partial, {annexIVSections.length - completedSections - partialSections} missing)
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[400] }}>
            This document is intended for regulatory compliance purposes under the EU AI Act.
          </Text>
        </View>
      </Page>

      {/* Page 1: Checklist Overview */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter generatedDate={generatedDate} />

        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Annex IV Documentation Checklist</Text>
          <Text style={baseStyles.paragraph}>
            Article 11 requires providers of high-risk AI systems to draw up technical documentation
            containing the elements set out in Annex IV. This checklist indicates the completion status
            of each required element.
          </Text>

          <View style={{ marginTop: 12 }}>
            {annexIVSections.map((section) => (
              <CheckItem
                key={section.key}
                text={section.label}
                status={getFieldStatus(section.value)}
              />
            ))}
          </View>

          <View style={[baseStyles.infoBox, { marginTop: 16 }]} wrap={false}>
            <Text style={baseStyles.infoBoxText}>
              Legend: ✓ Complete (documented) | ○ Partial (needs expansion) | ✗ Missing (not documented)
            </Text>
          </View>
        </View>
      </Page>

      {/* Page 2-3: Documentation Content */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter generatedDate={generatedDate} />

        {annexIVSections.slice(0, 6).map((section, idx) => (
          <View key={section.key} style={baseStyles.sectionKeepTogether}>
            <Text style={baseStyles.sectionTitle}>{section.label}</Text>
            <Text style={baseStyles.paragraph}>
              {section.value || "Documentation not yet provided. This section requires completion before conformity assessment."}
            </Text>
          </View>
        ))}
      </Page>

      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter generatedDate={generatedDate} />

        {annexIVSections.slice(6).map((section, idx) => (
          <View key={section.key} style={baseStyles.sectionKeepTogether}>
            <Text style={baseStyles.sectionTitle}>{section.label}</Text>
            <Text style={baseStyles.paragraph}>
              {section.value || "Documentation not yet provided. This section requires completion before conformity assessment."}
            </Text>
          </View>
        ))}
      </Page>

      {/* Risk Management Records */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter generatedDate={generatedDate} />

        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Risk Management Records (Article 9)</Text>
          <Text style={baseStyles.paragraph}>
            The following risks have been identified and documented as part of the risk management
            system required under Article 9 of the EU AI Act.
          </Text>

          {riskRecords.length > 0 ? (
            <View style={baseStyles.table}>
              <View style={baseStyles.tableHeader}>
                <Text style={[baseStyles.tableHeaderCellWide]}>Hazard</Text>
                <Text style={baseStyles.tableHeaderCell}>Category</Text>
                <Text style={baseStyles.tableHeaderCell}>Severity</Text>
                <Text style={baseStyles.tableHeaderCell}>Status</Text>
              </View>
              {riskRecords.map((risk, idx) => (
                <View
                  key={risk.id}
                  style={idx % 2 === 0 ? baseStyles.tableRow : baseStyles.tableRowAlt}
                  wrap={false}
                >
                  <Text style={baseStyles.tableCellWide}>{risk.hazard}</Text>
                  <Text style={baseStyles.tableCell}>{risk.hazard_category}</Text>
                  <Text style={baseStyles.tableCell}>{risk.severity}</Text>
                  <Text style={baseStyles.tableCell}>{risk.status}</Text>
                </View>
              ))}
            </View>
          ) : (
            <View style={baseStyles.warningBox} wrap={false}>
              <Text style={baseStyles.warningBoxText}>
                No risk records have been documented. Article 9 requires a risk management system
                to be established throughout the entire lifecycle of a high-risk AI system.
              </Text>
            </View>
          )}
        </View>

        {/* Dataset Registry */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Dataset Registry (Article 10)</Text>
          <Text style={baseStyles.paragraph}>
            Datasets used for training, validation, and testing must meet data governance and
            management practices requirements under Article 10.
          </Text>

          {datasets.length > 0 ? (
            <View style={baseStyles.table}>
              <View style={baseStyles.tableHeader}>
                <Text style={baseStyles.tableHeaderCellWide}>Dataset Name</Text>
                <Text style={baseStyles.tableHeaderCellWide}>Purpose</Text>
                <Text style={baseStyles.tableHeaderCell}>Quality Verified</Text>
              </View>
              {datasets.map((ds, idx) => (
                <View
                  key={ds.id}
                  style={idx % 2 === 0 ? baseStyles.tableRow : baseStyles.tableRowAlt}
                  wrap={false}
                >
                  <Text style={baseStyles.tableCellWide}>{ds.name}</Text>
                  <Text style={baseStyles.tableCellWide}>{ds.purpose || "Not specified"}</Text>
                  <Text style={baseStyles.tableCell}>{ds.data_quality_verified ? "Yes" : "No"}</Text>
                </View>
              ))}
            </View>
          ) : (
            <View style={baseStyles.infoBox} wrap={false}>
              <Text style={baseStyles.infoBoxText}>
                No datasets have been registered. This may be acceptable if the AI system does not
                use training data, or may indicate incomplete documentation.
              </Text>
            </View>
          )}
        </View>
      </Page>
    </Document>
  );
}
