import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors } from "@/lib/pdfStyles";

const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  ceMarkBox: {
    alignItems: "center",
    justifyContent: "center",
    padding: 30,
    marginVertical: 20,
    borderWidth: 2,
    borderColor: colors.gray[800],
    borderRadius: 8,
    backgroundColor: colors.gray[50],
  },
  ceMark: {
    fontSize: 72,
    fontWeight: 700,
    color: colors.gray[900],
    letterSpacing: 4,
  },
  ceSubtext: {
    fontSize: 10,
    color: colors.gray[600],
    marginTop: 8,
    textAlign: "center",
  },
  requirementRow: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "flex-start",
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
  requirementIcon: {
    width: 22,
    fontSize: 12,
    fontWeight: 700,
  },
  requirementMet: {
    color: colors.success,
  },
  requirementNotMet: {
    color: colors.danger,
  },
  requirementPending: {
    color: colors.warning,
  },
  requirementContent: {
    flex: 1,
  },
  requirementTitle: {
    fontSize: 10,
    fontWeight: 600,
    color: colors.gray[800],
    marginBottom: 2,
  },
  requirementDesc: {
    fontSize: 9,
    color: colors.gray[600],
  },
});

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>CE Marking Record — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer
function RunningFooter() {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export interface CEMarkingRecord {
  id: string;
  marking_type: string;
  location_description?: string | null;
  notified_body_number?: string | null;
  notified_body_id_displayed?: boolean | null;
  verified_at?: string | null;
  verified_by?: string | null;
  notes?: string | null;
  created_at: string;
}

interface CEMarkingPDFProps {
  ceRecord: CEMarkingRecord;
  systemName: string;
  versionLabel: string;
  organizationName: string;
  verifierName?: string;
  hasDeclaration: boolean;
  hasConformityAssessment: boolean;
  hasTechnicalDocs: boolean;
}

export function CEMarkingPDF({
  ceRecord,
  systemName,
  versionLabel,
  organizationName,
  verifierName,
  hasDeclaration,
  hasConformityAssessment,
  hasTechnicalDocs,
}: CEMarkingPDFProps) {
  const generatedDate = format(new Date(), "PPP");

  const requirements = [
    {
      id: "tech_docs",
      title: "Technical Documentation (Annex IV)",
      description: "Complete technical documentation as required by Article 11 and Annex IV.",
      met: hasTechnicalDocs,
    },
    {
      id: "conformity",
      title: "Conformity Assessment (Article 43)",
      description: "Conformity assessment completed through internal control or notified body involvement.",
      met: hasConformityAssessment,
    },
    {
      id: "declaration",
      title: "EU Declaration of Conformity (Annex V)",
      description: "Signed EU declaration of conformity as specified in Article 47 and Annex V.",
      met: hasDeclaration,
    },
    {
      id: "qms",
      title: "Quality Management System (Article 17)",
      description: "Documented QMS procedures ensuring ongoing compliance.",
      met: true, // Assumed if CE marking is being applied
    },
    {
      id: "marking",
      title: "CE Marking Applied (Article 48)",
      description: "CE marking affixed to the AI system or accompanying documentation.",
      met: !!ceRecord.verified_at,
    },
  ];

  const allRequirementsMet = requirements.every(r => r.met);

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={baseStyles.coverPage}>
        <View>
          <Text style={baseStyles.coverBadge}>EU AI ACT — ARTICLE 48</Text>
          <Text style={baseStyles.coverTitle}>CE Marking Record</Text>
          <Text style={baseStyles.coverSubtitle}>Conformity Marking Documentation</Text>
          <Text style={baseStyles.coverSystemName}>{systemName}</Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Version: </Text>{versionLabel}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Marking Type: </Text>{ceRecord.marking_type}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Organization: </Text>{organizationName}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Status: </Text>
            {ceRecord.verified_at ? "VERIFIED & APPLIED" : "PENDING VERIFICATION"}
          </Text>
        </View>

        <View style={baseStyles.coverFooter}>
          <Text style={{ fontSize: 10, color: colors.gray[500], marginBottom: 4 }}>
            Generated: {generatedDate}
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[400] }}>
            CE marking indicates conformity with EU AI Act requirements for high-risk AI systems.
          </Text>
        </View>
      </Page>

      {/* CE Marking Details */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter />

        {/* CE Mark Display */}
        <View style={styles.ceMarkBox}>
          <Text style={styles.ceMark}>CE</Text>
          {ceRecord.notified_body_number && ceRecord.notified_body_id_displayed && (
            <Text style={{ fontSize: 20, fontWeight: 700, color: colors.gray[800], marginTop: 4 }}>
              {ceRecord.notified_body_number}
            </Text>
          )}
          <Text style={styles.ceSubtext}>
            Conformity marking affixed under Article 48 of the EU AI Act
          </Text>
        </View>

        {/* Marking Details */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Marking Record Details</Text>
          
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Marking Type:</Text>
            <Text style={baseStyles.rowValue}>{ceRecord.marking_type}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Location:</Text>
            <Text style={baseStyles.rowValue}>{ceRecord.location_description || "Not specified"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Notified Body Number:</Text>
            <Text style={baseStyles.rowValue}>{ceRecord.notified_body_number || "N/A (internal assessment)"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verified At:</Text>
            <Text style={baseStyles.rowValue}>
              {ceRecord.verified_at ? format(new Date(ceRecord.verified_at), "PPP") : "Pending verification"}
            </Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verified By:</Text>
            <Text style={baseStyles.rowValue}>{verifierName || "Not yet verified"}</Text>
          </View>
          {ceRecord.notes && (
            <View style={{ marginTop: 8 }}>
              <Text style={baseStyles.h3}>Notes</Text>
              <Text style={baseStyles.paragraph}>{ceRecord.notes}</Text>
            </View>
          )}
        </View>

        {/* Prerequisites Checklist */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>CE Marking Prerequisites</Text>
          <Text style={baseStyles.paragraph}>
            Article 48 requires that CE marking can only be affixed after all conformity requirements
            have been fulfilled. The following checklist summarizes prerequisite completion status.
          </Text>

          <View style={{ marginTop: 12 }}>
            {requirements.map((req) => (
              <View key={req.id} style={styles.requirementRow} wrap={false}>
                <Text style={[
                  styles.requirementIcon,
                  req.met ? styles.requirementMet : styles.requirementNotMet
                ]}>
                  {req.met ? "✓" : "✗"}
                </Text>
                <View style={styles.requirementContent}>
                  <Text style={styles.requirementTitle}>{req.title}</Text>
                  <Text style={styles.requirementDesc}>{req.description}</Text>
                </View>
              </View>
            ))}
          </View>

          {allRequirementsMet ? (
            <View style={baseStyles.successBox} wrap={false}>
              <Text style={baseStyles.successBoxText}>
                All prerequisites have been met. The CE marking has been legitimately applied in
                accordance with Article 48 requirements.
              </Text>
            </View>
          ) : (
            <View style={baseStyles.warningBox} wrap={false}>
              <Text style={baseStyles.warningBoxText}>
                Some prerequisites are not yet complete. CE marking should only be affixed after
                all requirements are fulfilled.
              </Text>
            </View>
          )}
        </View>

        {/* Legal Information */}
        <View style={[baseStyles.infoBox, { marginTop: 16 }]} wrap={false}>
          <Text style={baseStyles.infoBoxText}>
            Article 48 Requirements: The CE marking shall be affixed visibly, legibly, and indelibly
            to the high-risk AI system or, where not possible, on its packaging or accompanying
            documentation. Where a notified body is involved, its identification number shall accompany
            the CE marking.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
