import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors } from "@/lib/pdfStyles";

const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  declarationBox: {
    borderWidth: 2,
    borderColor: colors.emerald,
    padding: 20,
    marginVertical: 15,
    borderRadius: 4,
  },
  declarationTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: colors.emerald,
    textAlign: "center",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  declarationText: {
    fontSize: 10,
    color: colors.gray[800],
    textAlign: "center",
    lineHeight: 1.8,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 8,
    fontWeight: 600,
    color: colors.gray[500],
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  fieldValue: {
    fontSize: 10,
    color: colors.gray[800],
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
  annexVItem: {
    flexDirection: "row",
    marginBottom: 8,
    alignItems: "flex-start",
  },
  annexVNumber: {
    width: 25,
    fontSize: 9,
    fontWeight: 600,
    color: colors.emerald,
  },
  annexVText: {
    flex: 1,
    fontSize: 9,
    color: colors.gray[700],
  },
  signatureArea: {
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: colors.gray[300],
  },
  signatureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  signatureBlock: {
    width: "45%",
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[800],
    marginTop: 50,
    marginBottom: 5,
  },
  signatureLabel: {
    fontSize: 8,
    color: colors.gray[500],
    textAlign: "center",
  },
});

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>EU Declaration of Conformity — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer
function RunningFooter() {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Official Document</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export interface EUDeclaration {
  id: string;
  declaration_number?: string | null;
  provider_name: string;
  provider_address?: string | null;
  provider_contact?: string | null;
  authorised_representative_name?: string | null;
  authorised_representative_address?: string | null;
  system_description?: string | null;
  conformity_procedure?: string | null;
  harmonised_standards?: string | null;
  common_specifications?: string | null;
  notified_body_name?: string | null;
  notified_body_number?: string | null;
  certificate_number?: string | null;
  place_of_issue?: string | null;
  date_of_issue?: string | null;
  signatory_name?: string | null;
  signatory_function?: string | null;
  signed_at?: string | null;
  status: string;
}

interface EUDeclarationPDFProps {
  declaration: EUDeclaration;
  systemName: string;
  versionLabel: string;
  organizationName: string;
}

export function EUDeclarationPDF({
  declaration,
  systemName,
  versionLabel,
  organizationName,
}: EUDeclarationPDFProps) {
  const generatedDate = format(new Date(), "PPP");

  const annexVElements = [
    { num: "1", label: "Provider name and address", value: `${declaration.provider_name}${declaration.provider_address ? `, ${declaration.provider_address}` : ""}` },
    { num: "2", label: "Authorised representative (if applicable)", value: declaration.authorised_representative_name || "N/A" },
    { num: "3", label: "AI system identification", value: `${systemName} (Version: ${versionLabel})` },
    { num: "4", label: "Description of AI system", value: declaration.system_description || "Not specified" },
    { num: "5", label: "Conformity assessment procedure", value: declaration.conformity_procedure || "Not specified" },
    { num: "6", label: "Harmonised standards applied", value: declaration.harmonised_standards || "None cited" },
    { num: "7", label: "Common specifications applied", value: declaration.common_specifications || "None cited" },
    { num: "8", label: "Notified body involvement", value: declaration.notified_body_name ? `${declaration.notified_body_name} (No. ${declaration.notified_body_number})` : "No notified body involvement" },
    { num: "9", label: "Certificate reference", value: declaration.certificate_number || "N/A" },
    { num: "10", label: "Place and date of issue", value: `${declaration.place_of_issue || "Not specified"}, ${declaration.date_of_issue ? format(new Date(declaration.date_of_issue), "PPP") : "Not dated"}` },
  ];

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={baseStyles.coverPage}>
        <View>
          <Text style={baseStyles.coverBadge}>EU AI ACT — ANNEX V</Text>
          <Text style={baseStyles.coverTitle}>EU Declaration of Conformity</Text>
          <Text style={baseStyles.coverSubtitle}>Article 47 Compliance Document</Text>
          <Text style={baseStyles.coverSystemName}>{systemName}</Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Declaration No: </Text>
            {declaration.declaration_number || "Not assigned"}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Version: </Text>{versionLabel}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Provider: </Text>{declaration.provider_name}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Status: </Text>
            {declaration.status === "signed" ? "SIGNED & ISSUED" : declaration.status.toUpperCase()}
          </Text>
        </View>

        <View style={baseStyles.coverFooter}>
          <Text style={{ fontSize: 10, color: colors.gray[500], marginBottom: 4 }}>
            Generated: {generatedDate}
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[400] }}>
            This EU Declaration of Conformity is issued under the sole responsibility of the provider.
          </Text>
        </View>
      </Page>

      {/* Declaration Content */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter />

        <View style={styles.declarationBox}>
          <Text style={styles.declarationTitle}>EU Declaration of Conformity</Text>
          <Text style={styles.declarationText}>
            This declaration of conformity is issued under the sole responsibility of the provider.
            The AI system described below is in conformity with the applicable requirements of
            Regulation (EU) 2024/1689 (EU AI Act).
          </Text>
        </View>

        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Annex V Required Elements</Text>
          <Text style={baseStyles.paragraph}>
            The following information is provided in accordance with Annex V of the EU AI Act,
            which specifies the content requirements for EU declarations of conformity.
          </Text>

          <View style={{ marginTop: 12 }}>
            {annexVElements.map((el) => (
              <View key={el.num} style={styles.annexVItem} wrap={false}>
                <Text style={styles.annexVNumber}>{el.num}.</Text>
                <View style={{ flex: 1 }}>
                  <Text style={[styles.fieldLabel, { marginBottom: 2 }]}>{el.label}</Text>
                  <Text style={styles.annexVText}>{el.value}</Text>
                </View>
              </View>
            ))}
          </View>
        </View>

        {/* Signature Section */}
        <View style={styles.signatureArea} wrap={false}>
          <Text style={baseStyles.h2}>Authorisation</Text>
          <Text style={baseStyles.paragraph}>
            This declaration is signed on behalf of the provider by the undersigned, 
            duly authorised to bind the provider.
          </Text>

          <View style={styles.signatureRow}>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Signature</Text>
              {declaration.signatory_name && (
                <Text style={{ fontSize: 9, color: colors.gray[700], textAlign: "center", marginTop: 4 }}>
                  {declaration.signatory_name}
                </Text>
              )}
              {declaration.signatory_function && (
                <Text style={{ fontSize: 8, color: colors.gray[500], textAlign: "center" }}>
                  {declaration.signatory_function}
                </Text>
              )}
            </View>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Date</Text>
              {declaration.signed_at && (
                <Text style={{ fontSize: 9, color: colors.gray[700], textAlign: "center", marginTop: 4 }}>
                  {format(new Date(declaration.signed_at), "PPP")}
                </Text>
              )}
            </View>
          </View>
        </View>

        {/* Legal Notice */}
        <View style={[baseStyles.infoBox, { marginTop: 20 }]} wrap={false}>
          <Text style={baseStyles.infoBoxText}>
            Legal Notice: The provider bears sole responsibility for drawing up and signing this
            EU declaration of conformity. This declaration must be kept at the disposal of national
            competent authorities for 10 years after the AI system has been placed on the market
            or put into service.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
