import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors, getRiskBadgeStyle, formatRiskLevel } from "@/lib/pdfStyles";
import { KLARVO_LOGO_URL } from "@/lib/pdfAssets";

const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  scoreCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 15,
    gap: 10,
  },
  scoreBox: {
    flex: 1,
    padding: 15,
    borderRadius: 4,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
  scoreValue: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 4,
  },
  scoreLabel: {
    fontSize: 8,
    color: colors.gray[500],
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  statusRow: {
    flexDirection: "row",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
    alignItems: "center",
  },
  statusLabel: {
    flex: 2,
    fontSize: 10,
    color: colors.gray[800],
  },
  statusValue: {
    flex: 1,
    fontSize: 10,
    fontWeight: 600,
    textAlign: "right",
  },
  statusComplete: {
    color: colors.success,
  },
  statusPartial: {
    color: colors.warning,
  },
  statusMissing: {
    color: colors.danger,
  },
  timelineItem: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "flex-start",
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 10,
    marginTop: 2,
  },
  timelineContent: {
    flex: 1,
  },
  timelineDate: {
    fontSize: 8,
    color: colors.gray[500],
    marginBottom: 2,
  },
  timelineTitle: {
    fontSize: 10,
    fontWeight: 600,
    color: colors.gray[800],
  },
});

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>Provider Compliance Summary — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer
function RunningFooter() {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export interface ProviderComplianceStatus {
  technicalDocsComplete: boolean;
  technicalDocsPercent: number;
  qmsDocumentsCount: number;
  conformityAssessmentStatus: string;
  declarationStatus: string;
  ceMarkingStatus: string;
  registrationStatus: string;
  monitoringPlanExists: boolean;
  incidentsCount: number;
  riskRecordsCount: number;
  datasetsCount: number;
}

export interface SystemInfo {
  name: string;
  description?: string | null;
  department?: string | null;
  lifecycle_status: string;
  created_at: string;
  classification?: {
    risk_level: string;
    is_high_risk_candidate?: boolean;
  } | null;
}

export interface VersionInfo {
  version_label: string;
  release_date?: string | null;
  status: string;
}

interface ProviderExecutiveSummaryPDFProps {
  system: SystemInfo;
  version: VersionInfo;
  complianceStatus: ProviderComplianceStatus;
  organizationName: string;
  generatedBy?: string;
}

export function ProviderExecutiveSummaryPDF({
  system,
  version,
  complianceStatus,
  organizationName,
  generatedBy,
}: ProviderExecutiveSummaryPDFProps) {
  const generatedDate = format(new Date(), "PPP");

  const getStatusStyle = (complete: boolean, partial?: boolean) => {
    if (complete) return styles.statusComplete;
    if (partial) return styles.statusPartial;
    return styles.statusMissing;
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case "signed":
      case "approved":
      case "verified":
      case "registered":
        return "Complete";
      case "draft":
      case "pending":
      case "in_progress":
        return "In Progress";
      default:
        return "Not Started";
    }
  };

  // Calculate overall readiness score
  const readinessFactors = [
    complianceStatus.technicalDocsPercent >= 80,
    complianceStatus.qmsDocumentsCount >= 5,
    complianceStatus.conformityAssessmentStatus === "approved",
    complianceStatus.declarationStatus === "signed",
    complianceStatus.ceMarkingStatus === "verified",
    complianceStatus.registrationStatus === "registered",
    complianceStatus.monitoringPlanExists,
  ];
  const readinessScore = Math.round((readinessFactors.filter(Boolean).length / readinessFactors.length) * 100);

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={baseStyles.coverPage}>
        <View>
          <Image src={KLARVO_LOGO_URL} style={{ width: 80, marginBottom: 25 }} />
          <Text style={baseStyles.coverBadge}>PROVIDER COMPLIANCE PACK</Text>
          <Text style={baseStyles.coverTitle}>Executive Summary</Text>
          <Text style={baseStyles.coverSubtitle}>EU AI Act Provider Obligations</Text>
          <Text style={baseStyles.coverSystemName}>{system.name}</Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Version: </Text>{version.version_label}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Organization: </Text>{organizationName}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Classification: </Text>
            {system.classification ? formatRiskLevel(system.classification.risk_level) : "Not Classified"}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Readiness Score: </Text>{readinessScore}%
          </Text>
        </View>

        <View style={baseStyles.coverFooter}>
          <Text style={{ fontSize: 10, color: colors.gray[500], marginBottom: 4 }}>
            Generated: {generatedDate}{generatedBy ? ` by ${generatedBy}` : ""}
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[400] }}>
            This pack contains documentation for EU AI Act provider compliance.
          </Text>
        </View>
      </Page>

      {/* Compliance Dashboard */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={system.name} orgName={organizationName} />
        <RunningFooter />

        {/* Score Cards */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Compliance Readiness</Text>
          
          <View style={styles.scoreCard}>
            <View style={[styles.scoreBox, { backgroundColor: readinessScore >= 80 ? colors.successLight : readinessScore >= 50 ? colors.warningLight : colors.dangerLight }]}>
              <Text style={[styles.scoreValue, { color: readinessScore >= 80 ? colors.success : readinessScore >= 50 ? colors.warning : colors.danger }]}>
                {readinessScore}%
              </Text>
              <Text style={styles.scoreLabel}>Overall Readiness</Text>
            </View>
            <View style={styles.scoreBox}>
              <Text style={[styles.scoreValue, { color: colors.emerald }]}>
                {complianceStatus.technicalDocsPercent}%
              </Text>
              <Text style={styles.scoreLabel}>Tech Docs Complete</Text>
            </View>
            <View style={styles.scoreBox}>
              <Text style={[styles.scoreValue, { color: colors.purple }]}>
                {complianceStatus.qmsDocumentsCount}
              </Text>
              <Text style={styles.scoreLabel}>QMS Documents</Text>
            </View>
          </View>
        </View>

        {/* System Overview */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>AI System Overview</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>System Name:</Text>
            <Text style={baseStyles.rowValue}>{system.name}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Version:</Text>
            <Text style={baseStyles.rowValue}>{version.version_label} ({version.status})</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Department:</Text>
            <Text style={baseStyles.rowValue}>{system.department || "Not specified"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Lifecycle Status:</Text>
            <Text style={baseStyles.rowValue}>{system.lifecycle_status}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Classification:</Text>
            <View style={[baseStyles.badge, getRiskBadgeStyle(system.classification?.risk_level || "not_classified")]}>
              <Text>{formatRiskLevel(system.classification?.risk_level || "not_classified")}</Text>
            </View>
          </View>
          {system.description && (
            <View style={{ marginTop: 8 }}>
              <Text style={baseStyles.h3}>Description</Text>
              <Text style={baseStyles.paragraph}>{system.description}</Text>
            </View>
          )}
        </View>

        {/* Compliance Status */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Provider Obligations Status</Text>
          
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>Technical Documentation (Annex IV)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.technicalDocsPercent >= 80, complianceStatus.technicalDocsPercent > 0)]}>
              {complianceStatus.technicalDocsPercent}% Complete
            </Text>
          </View>
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>Quality Management System (Article 17)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.qmsDocumentsCount >= 5, complianceStatus.qmsDocumentsCount > 0)]}>
              {complianceStatus.qmsDocumentsCount} Documents
            </Text>
          </View>
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>Conformity Assessment (Article 43)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.conformityAssessmentStatus === "approved", complianceStatus.conformityAssessmentStatus !== "not_started")]}>
              {getStatusText(complianceStatus.conformityAssessmentStatus)}
            </Text>
          </View>
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>EU Declaration of Conformity (Annex V)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.declarationStatus === "signed", complianceStatus.declarationStatus !== "not_started")]}>
              {getStatusText(complianceStatus.declarationStatus)}
            </Text>
          </View>
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>CE Marking (Article 48)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.ceMarkingStatus === "verified", complianceStatus.ceMarkingStatus !== "not_started")]}>
              {getStatusText(complianceStatus.ceMarkingStatus)}
            </Text>
          </View>
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>EU Database Registration (Article 49)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.registrationStatus === "registered", complianceStatus.registrationStatus !== "not_started")]}>
              {getStatusText(complianceStatus.registrationStatus)}
            </Text>
          </View>
          <View style={styles.statusRow} wrap={false}>
            <Text style={styles.statusLabel}>Post-Market Monitoring (Article 72)</Text>
            <Text style={[styles.statusValue, getStatusStyle(complianceStatus.monitoringPlanExists)]}>
              {complianceStatus.monitoringPlanExists ? "Plan Established" : "Not Started"}
            </Text>
          </View>
        </View>

        {/* Risk & Incident Summary */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>Risk & Incident Metrics</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Risk Records Documented:</Text>
            <Text style={baseStyles.rowValue}>{complianceStatus.riskRecordsCount}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Datasets Registered:</Text>
            <Text style={baseStyles.rowValue}>{complianceStatus.datasetsCount}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Serious Incidents Reported:</Text>
            <Text style={baseStyles.rowValue}>{complianceStatus.incidentsCount}</Text>
          </View>
        </View>

        {/* Recommendations */}
        {readinessScore < 100 && (
          <View style={baseStyles.warningBox} wrap={false}>
            <Text style={baseStyles.warningBoxText}>
              Action Required: The readiness score indicates incomplete compliance documentation.
              Review each obligation status above and complete missing elements before placing the
              AI system on the market or putting it into service.
            </Text>
          </View>
        )}
      </Page>
    </Document>
  );
}
