import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";
import { format } from "date-fns";
import { baseStyles, colors } from "@/lib/pdfStyles";
import { KLARVO_LOGO_BASE64 } from "@/lib/pdfAssets";

const styles = StyleSheet.create({
  page: {
    ...baseStyles.page,
    paddingTop: 60,
  },
  checklistTable: {
    marginTop: 10,
  },
  checklistHeader: {
    flexDirection: "row",
    backgroundColor: colors.emerald,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  checklistHeaderText: {
    fontSize: 9,
    fontWeight: 700,
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  checklistRow: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
    backgroundColor: "#fff",
  },
  checklistRowAlt: {
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
    backgroundColor: colors.gray[50],
  },
  checklistItem: {
    width: "70%",
    fontSize: 9,
    color: colors.gray[800],
  },
  checklistStatus: {
    width: "30%",
    fontSize: 9,
    textAlign: "center",
    fontWeight: 600,
  },
  statusCompliant: {
    color: colors.success,
  },
  statusNonCompliant: {
    color: colors.danger,
  },
  statusPending: {
    color: colors.warning,
  },
  escalationAlert: {
    backgroundColor: colors.dangerLight,
    borderWidth: 2,
    borderColor: colors.danger,
    borderRadius: 6,
    padding: 16,
    marginVertical: 15,
  },
  escalationTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: colors.danger,
    marginBottom: 8,
  },
  escalationText: {
    fontSize: 10,
    color: "#991b1b",
    lineHeight: 1.6,
  },
  statusCard: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  statusBox: {
    flex: 1,
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.gray[200],
    alignItems: "center",
  },
  statusBoxValue: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 4,
  },
  statusBoxLabel: {
    fontSize: 8,
    color: colors.gray[500],
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textAlign: "center",
  },
});

// Running Header
function RunningHeader({ systemName, orgName }: { systemName: string; orgName: string }) {
  return (
    <View style={baseStyles.runningHeader} fixed>
      <Text style={baseStyles.runningHeaderTitle}>Distributor Verification — {systemName}</Text>
      <Text style={baseStyles.runningHeaderOrg}>{orgName}</Text>
    </View>
  );
}

// Running Footer
function RunningFooter() {
  return (
    <View style={baseStyles.runningFooter} fixed>
      <Text style={baseStyles.footerText}>Generated by Klarvo EU AI Act Compliance Hub</Text>
      <Text style={baseStyles.footerConfidential}>Confidential</Text>
      <Text style={baseStyles.footerPage} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

export interface DistributorVerificationData {
  id: string;
  ai_system_id: string;
  verification_data: Record<string, boolean | null>;
  has_rebranded: boolean;
  has_modified: boolean;
  escalation_to_provider_triggered: boolean;
  escalation_notes: string | null;
  status: string;
  non_compliance_details: string | null;
  corrective_actions_taken: string | null;
  verified_by: string | null;
  verified_at: string | null;
  notes: string | null;
  created_at: string;
}

interface DistributorVerificationPDFProps {
  verification: DistributorVerificationData;
  systemName: string;
  organizationName: string;
  verifierName?: string;
  generatedBy: string;
}

const CHECKLIST_LABELS: Record<string, string> = {
  ce_marking_present: "CE marking is present and visible",
  doc_accompanies_system: "EU declaration of conformity accompanies the system",
  instructions_for_use_present: "Instructions for use are provided",
  provider_identified: "Provider is clearly identified",
  importer_identified: "Importer is identified (if applicable)",
  storage_transport_compliant: "Storage and transport conditions maintain compliance",
  no_modifications_made: "No modifications have been made to the AI system",
  no_rebranding_done: "No rebranding has been performed",
};

function getStatusText(value: boolean | null): string {
  if (value === true) return "✓ Verified";
  if (value === false) return "✗ Not Verified";
  return "○ Pending";
}

function getStatusStyle(value: boolean | null) {
  if (value === true) return styles.statusCompliant;
  if (value === false) return styles.statusNonCompliant;
  return styles.statusPending;
}

export function DistributorVerificationPDF({
  verification,
  systemName,
  organizationName,
  verifierName,
  generatedBy,
}: DistributorVerificationPDFProps) {
  const generatedDate = format(new Date(), "PPP");
  const checklistItems = Object.entries(verification.verification_data || {});
  const completedCount = checklistItems.filter(([_, v]) => v === true).length;
  const totalCount = checklistItems.length || Object.keys(CHECKLIST_LABELS).length;
  const completionPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  const statusDisplay = verification.status?.replace(/_/g, " ").toUpperCase() || "PENDING";

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={baseStyles.coverPage}>
        <View>
          <Image src={KLARVO_LOGO_BASE64} style={{ width: 80, marginBottom: 25 }} />
          <Text style={baseStyles.coverBadge}>EU AI ACT — ARTICLE 24</Text>
          <Text style={baseStyles.coverTitle}>Distributor Verification</Text>
          <Text style={baseStyles.coverSubtitle}>Supply Chain Compliance Record</Text>
          <Text style={baseStyles.coverSystemName}>{systemName}</Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Organization: </Text>{organizationName}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Status: </Text>{statusDisplay}
          </Text>
          <Text style={baseStyles.coverMeta}>
            <Text style={baseStyles.coverMetaLabel}>Completion: </Text>{completionPercent}% ({completedCount} of {totalCount} verified)
          </Text>
          {verification.escalation_to_provider_triggered && (
            <Text style={[baseStyles.coverMeta, { color: colors.danger, fontWeight: 700 }]}>
              <Text style={baseStyles.coverMetaLabel}>⚠ ESCALATION: </Text>Provider obligations may apply
            </Text>
          )}
        </View>

        <View style={baseStyles.coverFooter}>
          <Text style={{ fontSize: 10, color: colors.gray[500], marginBottom: 4 }}>
            Generated: {generatedDate}{generatedBy ? ` by ${generatedBy}` : ""}
          </Text>
          <Text style={{ fontSize: 8, color: colors.gray[400] }}>
            Distributors must verify compliance before making AI systems available on the market.
          </Text>
        </View>
      </Page>

      {/* Verification Record */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter />

        {/* Escalation Alert - Priority if triggered */}
        {verification.escalation_to_provider_triggered && (
          <View style={styles.escalationAlert} wrap={false}>
            <Text style={styles.escalationTitle}>⚠ Article 25 Escalation Triggered</Text>
            <Text style={styles.escalationText}>
              This distributor may be considered a Provider under Article 25 of the EU AI Act due to:
              {verification.has_rebranded && "\n• Rebranding the AI system under their name/trademark"}
              {verification.has_modified && "\n• Making substantial modifications to the AI system"}
              {"\n\n"}Provider obligations under Articles 16-22 may apply. Legal review recommended.
            </Text>
            {verification.escalation_notes && (
              <Text style={[styles.escalationText, { marginTop: 8, fontStyle: "italic" }]}>
                Notes: {verification.escalation_notes}
              </Text>
            )}
          </View>
        )}

        {/* Overview Section */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>1. Verification Overview</Text>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>AI System:</Text>
            <Text style={baseStyles.rowValue}>{systemName}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Distributor Organization:</Text>
            <Text style={baseStyles.rowValue}>{organizationName}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verification Status:</Text>
            <Text style={baseStyles.rowValue}>{statusDisplay}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verified By:</Text>
            <Text style={baseStyles.rowValue}>{verifierName || "Pending verification"}</Text>
          </View>
          <View style={baseStyles.row}>
            <Text style={baseStyles.rowLabel}>Verified Date:</Text>
            <Text style={baseStyles.rowValue}>
              {verification.verified_at ? format(new Date(verification.verified_at), "PPP") : "Not yet verified"}
            </Text>
          </View>
        </View>

        {/* Modification & Rebranding Status */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>2. Modification & Rebranding Assessment</Text>
          <Text style={baseStyles.paragraph}>
            Article 25 of the EU AI Act states that distributors who rebrand an AI system or make substantial
            modifications shall be considered providers and must comply with provider obligations.
          </Text>

          <View style={styles.statusCard}>
            <View style={[styles.statusBox, { backgroundColor: verification.has_rebranded ? colors.dangerLight : colors.successLight }]}>
              <Text style={[styles.statusBoxValue, { color: verification.has_rebranded ? colors.danger : colors.success }]}>
                {verification.has_rebranded ? "YES" : "NO"}
              </Text>
              <Text style={styles.statusBoxLabel}>Rebranding Performed</Text>
            </View>
            <View style={[styles.statusBox, { backgroundColor: verification.has_modified ? colors.dangerLight : colors.successLight }]}>
              <Text style={[styles.statusBoxValue, { color: verification.has_modified ? colors.danger : colors.success }]}>
                {verification.has_modified ? "YES" : "NO"}
              </Text>
              <Text style={styles.statusBoxLabel}>Modifications Made</Text>
            </View>
            <View style={[styles.statusBox, { backgroundColor: verification.escalation_to_provider_triggered ? colors.dangerLight : colors.gray[50] }]}>
              <Text style={[styles.statusBoxValue, { color: verification.escalation_to_provider_triggered ? colors.danger : colors.success }]}>
                {verification.escalation_to_provider_triggered ? "YES" : "NO"}
              </Text>
              <Text style={styles.statusBoxLabel}>Escalation Triggered</Text>
            </View>
          </View>
        </View>

        {/* Article 24 Checklist */}
        <View style={baseStyles.sectionKeepTogether}>
          <Text style={baseStyles.sectionTitle}>3. Article 24 Verification Checklist</Text>
          <Text style={baseStyles.paragraph}>
            Before making a high-risk AI system available on the market, distributors must verify
            the following requirements in accordance with Article 24 of the EU AI Act.
          </Text>

          <View style={styles.checklistTable}>
            <View style={styles.checklistHeader}>
              <Text style={[styles.checklistHeaderText, { width: "70%" }]}>Requirement</Text>
              <Text style={[styles.checklistHeaderText, { width: "30%", textAlign: "center" }]}>Status</Text>
            </View>
            {(checklistItems.length > 0 ? checklistItems : Object.entries(CHECKLIST_LABELS).map(([k]) => [k, null] as [string, boolean | null])).map(([key, value], idx) => (
              <View key={key} style={idx % 2 === 0 ? styles.checklistRow : styles.checklistRowAlt} wrap={false}>
                <Text style={styles.checklistItem}>
                  {CHECKLIST_LABELS[key] || key.replace(/_/g, " ")}
                </Text>
                <Text style={[styles.checklistStatus, getStatusStyle(value)]}>
                  {getStatusText(value)}
                </Text>
              </View>
            ))}
          </View>
        </View>
      </Page>

      {/* Page 2: Non-compliance, Notes, Signature */}
      <Page size="A4" style={styles.page}>
        <RunningHeader systemName={systemName} orgName={organizationName} />
        <RunningFooter />

        {/* Non-compliance & Corrective Actions */}
        {(verification.non_compliance_details || verification.corrective_actions_taken) && (
          <View style={baseStyles.sectionKeepTogether}>
            <Text style={baseStyles.sectionTitle}>4. Non-Compliance & Corrective Actions</Text>
            {verification.non_compliance_details && (
              <View style={baseStyles.dangerBox} wrap={false}>
                <Text style={{ fontSize: 10, fontWeight: 700, color: colors.danger, marginBottom: 6 }}>
                  Non-Compliance Identified
                </Text>
                <Text style={baseStyles.dangerBoxText}>{verification.non_compliance_details}</Text>
              </View>
            )}
            {verification.corrective_actions_taken && (
              <View style={baseStyles.infoBox} wrap={false}>
                <Text style={{ fontSize: 10, fontWeight: 700, color: colors.emerald, marginBottom: 6 }}>
                  Corrective Actions Taken
                </Text>
                <Text style={baseStyles.infoBoxText}>{verification.corrective_actions_taken}</Text>
              </View>
            )}
          </View>
        )}

        {/* Notes */}
        {verification.notes && (
          <View style={baseStyles.sectionKeepTogether}>
            <Text style={baseStyles.sectionTitle}>5. Additional Notes</Text>
            <View style={baseStyles.infoBox}>
              <Text style={baseStyles.infoBoxText}>{verification.notes}</Text>
            </View>
          </View>
        )}

        {/* Signature Section */}
        <View style={baseStyles.signatureSection} wrap={false}>
          <Text style={[baseStyles.h2, { marginTop: 0, marginBottom: 15 }]}>Verification Sign-off</Text>
          <Text style={baseStyles.paragraph}>
            This verification record confirms that the distributor has performed due diligence checks
            on the AI system's compliance status before making it available on the market.
          </Text>
          <View style={baseStyles.signatureRow}>
            <View style={baseStyles.signatureBlock}>
              <View style={baseStyles.signatureLine} />
              <Text style={baseStyles.signatureLabel}>Verified By</Text>
              {verifierName && (
                <Text style={{ fontSize: 9, color: colors.gray[800], marginTop: 2 }}>{verifierName}</Text>
              )}
              <Text style={{ fontSize: 8, color: colors.gray[500], marginTop: 2 }}>
                {verification.verified_at ? format(new Date(verification.verified_at), "PPP") : "Date: _______________"}
              </Text>
            </View>
            <View style={baseStyles.signatureBlock}>
              <View style={baseStyles.signatureLine} />
              <Text style={baseStyles.signatureLabel}>Compliance Officer Approval</Text>
              <Text style={{ fontSize: 8, color: colors.gray[500], marginTop: 2 }}>Date: _______________</Text>
            </View>
          </View>
        </View>

        {/* Legal Notice */}
        <View style={[baseStyles.warningBox, { marginTop: 20 }]} wrap={false}>
          <Text style={baseStyles.warningBoxText}>
            Article 24 Obligations: Distributors must verify that the AI system bears CE marking, is accompanied by
            an EU declaration of conformity and instructions for use, and that the provider and importer have complied
            with their obligations. Non-compliant systems must not be made available on the market.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
